--this file is created by xml2lua.makefile. don't modify it
require "Achievement"
require "Activity_Login"
require "Activity_Xiao"
require "Activity"
require "Cang_Goods"
require "Cang_Quan"
require "Cang_Rank"
require "Cang_Shop"
require "Con_Chong"
require "Drop"
require "GBoss"
require "HotPoint"
require "Lottery_Pool"
