// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartBeatResp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "heartBeatResp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* HeartBeatResp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HeartBeatResp_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* HeartBeatResp_Result_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_heartBeatResp_2eproto() {
  protobuf_AddDesc_heartBeatResp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "heartBeatResp.proto");
  GOOGLE_CHECK(file != NULL);
  HeartBeatResp_descriptor_ = file->message_type(0);
  static const int HeartBeatResp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartBeatResp, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartBeatResp, nowtime_),
  };
  HeartBeatResp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      HeartBeatResp_descriptor_,
      HeartBeatResp::default_instance_,
      HeartBeatResp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartBeatResp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartBeatResp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(HeartBeatResp));
  HeartBeatResp_Result_descriptor_ = HeartBeatResp_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_heartBeatResp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    HeartBeatResp_descriptor_, &HeartBeatResp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_heartBeatResp_2eproto() {
  delete HeartBeatResp::default_instance_;
  delete HeartBeatResp_reflection_;
}

void protobuf_AddDesc_heartBeatResp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023heartBeatResp.proto\"l\n\rHeartBeatResp\022%"
    "\n\006result\030\001 \002(\0162\025.HeartBeatResp.Result\022\017\n"
    "\007nowtime\030\002 \001(\003\"#\n\006Result\022\021\n\004FAIL\020\377\377\377\377\377\377\377"
    "\377\377\001\022\006\n\002OK\020\000", 131);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "heartBeatResp.proto", &protobuf_RegisterTypes);
  HeartBeatResp::default_instance_ = new HeartBeatResp();
  HeartBeatResp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_heartBeatResp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_heartBeatResp_2eproto {
  StaticDescriptorInitializer_heartBeatResp_2eproto() {
    protobuf_AddDesc_heartBeatResp_2eproto();
  }
} static_descriptor_initializer_heartBeatResp_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* HeartBeatResp_Result_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HeartBeatResp_Result_descriptor_;
}
bool HeartBeatResp_Result_IsValid(int value) {
  switch(value) {
    case -1:
    case 0:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const HeartBeatResp_Result HeartBeatResp::FAIL;
const HeartBeatResp_Result HeartBeatResp::OK;
const HeartBeatResp_Result HeartBeatResp::Result_MIN;
const HeartBeatResp_Result HeartBeatResp::Result_MAX;
const int HeartBeatResp::Result_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int HeartBeatResp::kResultFieldNumber;
const int HeartBeatResp::kNowtimeFieldNumber;
#endif  // !_MSC_VER

HeartBeatResp::HeartBeatResp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void HeartBeatResp::InitAsDefaultInstance() {
}

HeartBeatResp::HeartBeatResp(const HeartBeatResp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void HeartBeatResp::SharedCtor() {
  _cached_size_ = 0;
  result_ = -1;
  nowtime_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HeartBeatResp::~HeartBeatResp() {
  SharedDtor();
}

void HeartBeatResp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void HeartBeatResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HeartBeatResp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HeartBeatResp_descriptor_;
}

const HeartBeatResp& HeartBeatResp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_heartBeatResp_2eproto();
  return *default_instance_;
}

HeartBeatResp* HeartBeatResp::default_instance_ = NULL;

HeartBeatResp* HeartBeatResp::New() const {
  return new HeartBeatResp;
}

void HeartBeatResp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    result_ = -1;
    nowtime_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool HeartBeatResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .HeartBeatResp.Result result = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::HeartBeatResp_Result_IsValid(value)) {
            set_result(static_cast< ::HeartBeatResp_Result >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_nowtime;
        break;
      }

      // optional int64 nowtime = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_nowtime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &nowtime_)));
          set_has_nowtime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void HeartBeatResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .HeartBeatResp.Result result = 1;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->result(), output);
  }

  // optional int64 nowtime = 2;
  if (has_nowtime()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->nowtime(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* HeartBeatResp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .HeartBeatResp.Result result = 1;
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->result(), target);
  }

  // optional int64 nowtime = 2;
  if (has_nowtime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->nowtime(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int HeartBeatResp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .HeartBeatResp.Result result = 1;
    if (has_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->result());
    }

    // optional int64 nowtime = 2;
    if (has_nowtime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->nowtime());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HeartBeatResp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const HeartBeatResp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const HeartBeatResp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HeartBeatResp::MergeFrom(const HeartBeatResp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_result()) {
      set_result(from.result());
    }
    if (from.has_nowtime()) {
      set_nowtime(from.nowtime());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void HeartBeatResp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HeartBeatResp::CopyFrom(const HeartBeatResp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeartBeatResp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void HeartBeatResp::Swap(HeartBeatResp* other) {
  if (other != this) {
    std::swap(result_, other->result_);
    std::swap(nowtime_, other->nowtime_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata HeartBeatResp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HeartBeatResp_descriptor_;
  metadata.reflection = HeartBeatResp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
