# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarClient-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StarClient-desktop

end

target 'StarClient-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StarClient-mobile
  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'Flurry-iOS-SDK/FlurryAds'
  pod 'GA-SDK-IOS','~>2.2'
end

