local ACTIVITYGROUP = {}
ACTIVITYGROUP["index"] = {}
ACTIVITYGROUP["index"][1] = 1
ACTIVITYGROUP[1] = {}
	ACTIVITYGROUP[1]["ID"] = 1
	ACTIVITYGROUP[1]["MAIN_NAME"] = "ACTI_1"
	ACTIVITYGROUP[1]["MAIN_MEMO"] = "ACTI_MEMO_1"
	ACTIVITYGROUP[1]["MAIN_ICON"] = 3
	ACTIVITYGROUP[1]["SUB_ID"] = {}
		ACTIVITYGROUP[1]["SUB_ID"][1] = 1021
		ACTIVITYGROUP[1]["SUB_ID"][2] = 1022
	ACTIVITYGROUP[1]["real_idx"] = 1

ACTIVITYGROUP["index"][2] = 2
ACTIVITYGROUP[2] = {}
	ACTIVITYGROUP[2]["ID"] = 2
	ACTIVITYGROUP[2]["MAIN_NAME"] = "ACTI_2"
	ACTIVITYGROUP[2]["MAIN_MEMO"] = "ACTI_MEMO_2"
	ACTIVITYGROUP[2]["MAIN_ICON"] = 2
	ACTIVITYGROUP[2]["SUB_ID"] = {}
		ACTIVITYGROUP[2]["SUB_ID"][1] = 2021
	ACTIVITYGROUP[2]["real_idx"] = 2

ACTIVITYGROUP["index"][3] = 3
ACTIVITYGROUP[3] = {}
	ACTIVITYGROUP[3]["ID"] = 3
	ACTIVITYGROUP[3]["MAIN_NAME"] = "ACTI_3"
	ACTIVITYGROUP[3]["MAIN_MEMO"] = "ACTI_MEMO_3"
	ACTIVITYGROUP[3]["MAIN_ICON"] = 2
	ACTIVITYGROUP[3]["SUB_ID"] = {}
		ACTIVITYGROUP[3]["SUB_ID"][1] = 3021
	ACTIVITYGROUP[3]["real_idx"] = 3

ACTIVITYGROUP["index"][4] = 4
ACTIVITYGROUP[4] = {}
	ACTIVITYGROUP[4]["ID"] = 4
	ACTIVITYGROUP[4]["MAIN_NAME"] = "ACTI_4"
	ACTIVITYGROUP[4]["MAIN_MEMO"] = "ACTI_MEMO_4_1"
	ACTIVITYGROUP[4]["MAIN_ICON"] = 3
	ACTIVITYGROUP[4]["SUB_ID"] = {}
		ACTIVITYGROUP[4]["SUB_ID"][1] = 4001
	ACTIVITYGROUP[4]["real_idx"] = 4

ACTIVITYGROUP["index"][5] = 5
ACTIVITYGROUP[5] = {}
	ACTIVITYGROUP[5]["ID"] = 5
	ACTIVITYGROUP[5]["MAIN_NAME"] = "ACTI_5"
	ACTIVITYGROUP[5]["MAIN_MEMO"] = "ACTI_5"
	ACTIVITYGROUP[5]["MAIN_ICON"] = 0
	ACTIVITYGROUP[5]["SUB_ID"] = {}
		ACTIVITYGROUP[5]["SUB_ID"][1] = 5001
	ACTIVITYGROUP[5]["real_idx"] = 5

ACTIVITYGROUP["index"][6] = 6
ACTIVITYGROUP[6] = {}
	ACTIVITYGROUP[6]["ID"] = 6
	ACTIVITYGROUP[6]["MAIN_NAME"] = "ACTI_6"
	ACTIVITYGROUP[6]["MAIN_MEMO"] = "ACTI_6"
	ACTIVITYGROUP[6]["MAIN_ICON"] = 3
	ACTIVITYGROUP[6]["SUB_ID"] = {}
		ACTIVITYGROUP[6]["SUB_ID"][1] = 10001
	ACTIVITYGROUP[6]["real_idx"] = 6

ACTIVITYGROUP["index"][7] = 7
ACTIVITYGROUP[7] = {}
	ACTIVITYGROUP[7]["ID"] = 7
	ACTIVITYGROUP[7]["MAIN_NAME"] = "ACTI_7"
	ACTIVITYGROUP[7]["MAIN_MEMO"] = "ACTI_7"
	ACTIVITYGROUP[7]["MAIN_ICON"] = 2
	ACTIVITYGROUP[7]["SUB_ID"] = {}
		ACTIVITYGROUP[7]["SUB_ID"][1] = 12001
	ACTIVITYGROUP[7]["real_idx"] = 7

ACTIVITYGROUP["index"][8] = 8
ACTIVITYGROUP[8] = {}
	ACTIVITYGROUP[8]["ID"] = 8
	ACTIVITYGROUP[8]["MAIN_NAME"] = "ACTI_8"
	ACTIVITYGROUP[8]["MAIN_MEMO"] = "ACTI_8"
	ACTIVITYGROUP[8]["MAIN_ICON"] = 3
	ACTIVITYGROUP[8]["SUB_ID"] = {}
		ACTIVITYGROUP[8]["SUB_ID"][1] = 13001
	ACTIVITYGROUP[8]["real_idx"] = 8

ACTIVITYGROUP["index"][9] = 9
ACTIVITYGROUP[9] = {}
	ACTIVITYGROUP[9]["ID"] = 9
	ACTIVITYGROUP[9]["MAIN_NAME"] = "ACTI_10"
	ACTIVITYGROUP[9]["MAIN_MEMO"] = "ACTI_10"
	ACTIVITYGROUP[9]["MAIN_ICON"] = 0
	ACTIVITYGROUP[9]["SUB_ID"] = {}
		ACTIVITYGROUP[9]["SUB_ID"][1] = 14001
	ACTIVITYGROUP[9]["real_idx"] = 9

ACTIVITYGROUP["index"][10] = 10
ACTIVITYGROUP[10] = {}
	ACTIVITYGROUP[10]["ID"] = 10
	ACTIVITYGROUP[10]["MAIN_NAME"] = "ACTI_11"
	ACTIVITYGROUP[10]["MAIN_MEMO"] = "ACTI_11"
	ACTIVITYGROUP[10]["MAIN_ICON"] = 3
	ACTIVITYGROUP[10]["SUB_ID"] = {}
		ACTIVITYGROUP[10]["SUB_ID"][1] = 15001
	ACTIVITYGROUP[10]["real_idx"] = 10


ACTIVITYGROUP["len"] = 10

return ACTIVITYGROUP
