local SHIP_BLUEPRINTBREAK = {}
SHIP_BLUEPRINTBREAK["index"] = {}
SHIP_BLUEPRINTBREAK["index"][1] = 1
SHIP_BLUEPRINTBREAK[1] = {}
	SHIP_BLUEPRINTBREAK[1]["ID"] = 1
	SHIP_BLUEPRINTBREAK[1]["ITEM_NUM1"] = 2
	SHIP_BLUEPRINTBREAK[1]["ITEM_NUM2"] = 9
	SHIP_BLUEPRINTBREAK[1]["ITEM_NUM3"] = 0
	SHIP_BLUEPRINTBREAK[1]["ITEM_NUM4"] = 0
	SHIP_BLUEPRINTBREAK[1]["ITEM_NUM5"] = 0
	SHIP_BLUEPRINTBREAK[1]["ITEM_NUM6"] = 0
	SHIP_BLUEPRINTBREAK[1]["ITEM_NUM7"] = 0
	SHIP_BLUEPRINTBREAK[1]["ITEM_NUM8"] = 0
	SHIP_BLUEPRINTBREAK[1]["real_idx"] = 1

SHIP_BLUEPRINTBREAK["index"][2] = 2
SHIP_BLUEPRINTBREAK[2] = {}
	SHIP_BLUEPRINTBREAK[2]["ID"] = 2
	SHIP_BLUEPRINTBREAK[2]["ITEM_NUM1"] = 2
	SHIP_BLUEPRINTBREAK[2]["ITEM_NUM2"] = 11
	SHIP_BLUEPRINTBREAK[2]["ITEM_NUM3"] = 24
	SHIP_BLUEPRINTBREAK[2]["ITEM_NUM4"] = 0
	SHIP_BLUEPRINTBREAK[2]["ITEM_NUM5"] = 0
	SHIP_BLUEPRINTBREAK[2]["ITEM_NUM6"] = 0
	SHIP_BLUEPRINTBREAK[2]["ITEM_NUM7"] = 0
	SHIP_BLUEPRINTBREAK[2]["ITEM_NUM8"] = 0
	SHIP_BLUEPRINTBREAK[2]["real_idx"] = 2

SHIP_BLUEPRINTBREAK["index"][3] = 3
SHIP_BLUEPRINTBREAK[3] = {}
	SHIP_BLUEPRINTBREAK[3]["ID"] = 3
	SHIP_BLUEPRINTBREAK[3]["ITEM_NUM1"] = 2
	SHIP_BLUEPRINTBREAK[3]["ITEM_NUM2"] = 11
	SHIP_BLUEPRINTBREAK[3]["ITEM_NUM3"] = 25
	SHIP_BLUEPRINTBREAK[3]["ITEM_NUM4"] = 44
	SHIP_BLUEPRINTBREAK[3]["ITEM_NUM5"] = 0
	SHIP_BLUEPRINTBREAK[3]["ITEM_NUM6"] = 0
	SHIP_BLUEPRINTBREAK[3]["ITEM_NUM7"] = 0
	SHIP_BLUEPRINTBREAK[3]["ITEM_NUM8"] = 0
	SHIP_BLUEPRINTBREAK[3]["real_idx"] = 3

SHIP_BLUEPRINTBREAK["index"][4] = 4
SHIP_BLUEPRINTBREAK[4] = {}
	SHIP_BLUEPRINTBREAK[4]["ID"] = 4
	SHIP_BLUEPRINTBREAK[4]["ITEM_NUM1"] = 4
	SHIP_BLUEPRINTBREAK[4]["ITEM_NUM2"] = 16
	SHIP_BLUEPRINTBREAK[4]["ITEM_NUM3"] = 35
	SHIP_BLUEPRINTBREAK[4]["ITEM_NUM4"] = 61
	SHIP_BLUEPRINTBREAK[4]["ITEM_NUM5"] = 94
	SHIP_BLUEPRINTBREAK[4]["ITEM_NUM6"] = 134
	SHIP_BLUEPRINTBREAK[4]["ITEM_NUM7"] = 0
	SHIP_BLUEPRINTBREAK[4]["ITEM_NUM8"] = 0
	SHIP_BLUEPRINTBREAK[4]["real_idx"] = 4

SHIP_BLUEPRINTBREAK["index"][5] = 5
SHIP_BLUEPRINTBREAK[5] = {}
	SHIP_BLUEPRINTBREAK[5]["ID"] = 5
	SHIP_BLUEPRINTBREAK[5]["ITEM_NUM1"] = 6
	SHIP_BLUEPRINTBREAK[5]["ITEM_NUM2"] = 22
	SHIP_BLUEPRINTBREAK[5]["ITEM_NUM3"] = 48
	SHIP_BLUEPRINTBREAK[5]["ITEM_NUM4"] = 84
	SHIP_BLUEPRINTBREAK[5]["ITEM_NUM5"] = 128
	SHIP_BLUEPRINTBREAK[5]["ITEM_NUM6"] = 182
	SHIP_BLUEPRINTBREAK[5]["ITEM_NUM7"] = 246
	SHIP_BLUEPRINTBREAK[5]["ITEM_NUM8"] = 319
	SHIP_BLUEPRINTBREAK[5]["real_idx"] = 5


SHIP_BLUEPRINTBREAK["len"] = 5

return SHIP_BLUEPRINTBREAK
