local STRONGPOINT = {}
STRONGPOINT["index"] = {}
STRONGPOINT["index"][1] = 2
STRONGPOINT[2] = {}
	STRONGPOINT[2]["ID"] = 2
	STRONGPOINT[2]["NAME"] = "Strongpoint_1"
	STRONGPOINT[2]["OPEN_TIME"] = 360
	STRONGPOINT[2]["PEACE_TIME"] = 180
	STRONGPOINT[2]["FIGHT_TIME"] = 120
	STRONGPOINT[2]["TROOPS_LIMIT"] = 99
	STRONGPOINT[2]["BUFF"] = 33000315
	STRONGPOINT[2]["EVERYDAY_AWARD"] = 3203
	STRONGPOINT[2]["FIRST_AWARD"] = 3301
	STRONGPOINT[2]["EXPEND"] = 1
	STRONGPOINT[2]["SHIP"] = nil
	STRONGPOINT[2]["real_idx"] = 1

STRONGPOINT["index"][2] = 3
STRONGPOINT[3] = {}
	STRONGPOINT[3]["ID"] = 3
	STRONGPOINT[3]["NAME"] = "Strongpoint_2"
	STRONGPOINT[3]["OPEN_TIME"] = 360
	STRONGPOINT[3]["PEACE_TIME"] = 180
	STRONGPOINT[3]["FIGHT_TIME"] = 110
	STRONGPOINT[3]["TROOPS_LIMIT"] = 99
	STRONGPOINT[3]["BUFF"] = 33000315
	STRONGPOINT[3]["EVERYDAY_AWARD"] = 3203
	STRONGPOINT[3]["FIRST_AWARD"] = 3301
	STRONGPOINT[3]["EXPEND"] = 1
	STRONGPOINT[3]["SHIP"] = nil
	STRONGPOINT[3]["real_idx"] = 2

STRONGPOINT["index"][3] = 4
STRONGPOINT[4] = {}
	STRONGPOINT[4]["ID"] = 4
	STRONGPOINT[4]["NAME"] = "Strongpoint_3"
	STRONGPOINT[4]["OPEN_TIME"] = 360
	STRONGPOINT[4]["PEACE_TIME"] = 180
	STRONGPOINT[4]["FIGHT_TIME"] = 130
	STRONGPOINT[4]["TROOPS_LIMIT"] = 99
	STRONGPOINT[4]["BUFF"] = 33000315
	STRONGPOINT[4]["EVERYDAY_AWARD"] = 3203
	STRONGPOINT[4]["FIRST_AWARD"] = 3301
	STRONGPOINT[4]["EXPEND"] = 1
	STRONGPOINT[4]["SHIP"] = nil
	STRONGPOINT[4]["real_idx"] = 3

STRONGPOINT["index"][4] = 5
STRONGPOINT[5] = {}
	STRONGPOINT[5]["ID"] = 5
	STRONGPOINT[5]["NAME"] = "Strongpoint_4"
	STRONGPOINT[5]["OPEN_TIME"] = 360
	STRONGPOINT[5]["PEACE_TIME"] = 180
	STRONGPOINT[5]["FIGHT_TIME"] = 130
	STRONGPOINT[5]["TROOPS_LIMIT"] = 99
	STRONGPOINT[5]["BUFF"] = 33000315
	STRONGPOINT[5]["EVERYDAY_AWARD"] = 3203
	STRONGPOINT[5]["FIRST_AWARD"] = 3301
	STRONGPOINT[5]["EXPEND"] = 1
	STRONGPOINT[5]["SHIP"] = nil
	STRONGPOINT[5]["real_idx"] = 4


STRONGPOINT["len"] = 4

return STRONGPOINT
