
˛o
cmd_define.proto*Èo

CMD_DEFINE
CMD_BORDER_CLIENTÄ 
CMD_LOGIN_REQÅ 
CMD_LOGIN_RESPÇ 
CMD_LOGOUT_REQÉ 
CMD_LOGOUT_RESPÑ 
CMD_HEART_BEAT_REQÖ 
CMD_HEART_BEAT_RESPÜ 
CMD_REGIST_REQá 
ALIAS_REGIST_TO_LOGIN_RESPà 
CMD_USERLOG_REQâ  
CMD_QUERY_BEFORE_REGIST_REQä !
CMD_QUERY_BEFORE_REGIST_RESPã 
CMD_MOVE_IN_ROOM_REQê 
CMD_ROOM_SYNC_ON_LOGINë 
CMD_REG_INIT_SHIP_REQ† 
CMD_REG_INIT_SHIP_RESP° 
CMD_IS_ONLINE_REQ¢ 
CMD_IS_ONLINE_RESP£ 
CMD_GUIDE_STEP_REQ§ 
CMD_GUIDE_STEP_RESP• 
CMD_UPDATE_RES_REQ¶ 
CMD_UPDATE_RES_RESPß 
CMD_AID_AWARD_REQ® 
CMD_AID_AWARD_RESP© 
CMD_GET_STRENGTH_REQ∞ 
CMD_GET_STRENGTH_RESP± 
CMD_ADD_STRENGTH_REQ≤ 
CMD_ADD_STRENGTH_RESP≥ 
CMD_SERVER_RES_UPDATE¥ 
CMD_TASK_REFLEASH_RESPµ 
CMD_PLANET_USER_UPDATE∂ 
CMD_NOTIFY_REFLESH_RESP∑ 
CMD_PLANET_GET_REQ∏ 
CMD_PLANET_GET_RESPπ 
CMD_PLANET_COLLCT_REQ∫ 
CMD_PLANET_COLLCT_RESPª 
CMD_PVP_VIDEO_REQº 
CMD_PVP_VIDEO_RESPΩ 
CMD_PLANET_SPEED_UP_REQæ 
CMD_PLANET_SPEED_UP_RESPø 
CMD_PLANET_RUINS_REQ¿ 
CMD_PLANET_RUINS_RESP¡ 
CMD_PLANET_MOVE_BASE_REQ¬ 
CMD_PLANET_MOVE_BASE_RESP√ 
CMD_PLANET_RIDE_BACK_REQƒ 
CMD_PLANET_RIDE_BACK_RESP≈ 
CMD_PLANET_RAID_REQ∆ 
CMD_PLANET_RAID_RESP« 
CMD_PLANET_MARK_REQ» 
CMD_PLANET_MARK_RESP… 
CMD_PLANET_SHIELD_BASE_REQ   
CMD_PLANET_SHIELD_BASE_RESPÀ 
CMD_PLANET_TOWER_REQÃ 
CMD_PLANET_TOWER_RESPÕ  
CMD_PANET_WANGZUO_TITLE_REQŒ !
CMD_PANET_WANGZUO_TITLE_RESPœ 
CMD_GET_KNIGHT_BAG_REQ– 
CMD_GET_KNIGHT_BAG_RESP— 
CMD_GET_ITEM_PACKAGE_REQ“ 
CMD_GET_ITEM_PACKAGE_RESP” 
CMD_UPDATE_TIMESTAMP_REQ‘ 
CMD_UPDATE_TIMESTAMP_RESP’ 
CMD_CLIENT_CODE_SET_REQÿ 
CMD_CLIENT_CODE_SET_RESPŸ 
CMD_GET_EXTDATA_AT_5AM_REQ⁄  
CMD_GET_EXTDATA_AT_5AM_RESP€ 
CMD_GET_HUODONG_FLAG_REQ‹ 
CMD_GET_HUODONG_FLAG_RESP› 
CMD_OPEN_CHEST_REQﬁ 
CMD_OPEN_CHEST_RESPﬂ 
CMD_SELL_ITEM_REQ‡ 
CMD_SELL_ITEM_RESP· 
CMD_TILI_REWARD_REQ‚ 
CMD_TILI_REWARD_RESP„ 
CMD_OPEN_GIFT_REQ‰ 
CMD_OPEN_GIFT_RESPÂ 
CMD_REFLESH_QIYU_REQÊ 
CMD_REFLESH_QIYU_RESPÁ 
CMD_GET_QIYU_REQË 
CMD_GET_QIYU_RESPÈ 
CMD_DEL_QIYU_REQÍ 
CMD_DEL_QIYU_RESPÎ 
CMD_SHIP_FIX_REQ˛!
CMD_SHIP_FIX_RESPˇ!
CMD_GET_SHIP_LIST_REQÄ"
CMD_GET_SHIP_LIST_RESPÅ"
CMD_CHANGE_LINEUP_REQÇ"
CMD_CHANGE_LINEUP_RESPÉ"
CMD_CHANGE_WEAPON_REQÑ"
CMD_CHANGE_WEAPON_RESPÖ"
CMD_SHIP_DEVELOPE_REQÜ"
CMD_SHIP_DEVELOPE_RESPá"
CMD_BLUEPRINT_DEVELOPE_REQà" 
CMD_BLUEPRINT_DEVELOPE_RESPâ"
CMD_SHIP_CREATE_REQä"
CMD_SHIP_CREATE_RESPã"
CMD_SHIP_REMOVE_REQå"
CMD_SHIP_REMOVE_RESPç"
CMD_SHIP_EQUIP_REQé"
CMD_SHIP_EQUIP_RESPè"
CMD_TRADE_GET_MONEY_REQê"
CMD_TRADE_GET_MONEY_RESPë"
CMD_WEAPON_UPGRADE_REQí"
CMD_WEAPON_UPGRADE_RESPì"
CMD_GET_HOME_STATUS_REQî"
CMD_GET_HOME_STATUS_RESPï"
CMD_GET_RESOURCE_REQñ"
CMD_GET_RESOURCE_RESPó"
CMD_UPGRADE_RESOURCE_REQò"
CMD_UPGRADE_RESOURCE_RESPô"
CMD_REMOVE_RESOURCE_REQö"
CMD_REMOVE_RESOURCE_RESPõ"
CMD_CANCEL_BUILD_REQú"
CMD_CANCEL_BUILD_RESPù"
CMD_SPEED_UP_BUILD_REQû"
CMD_SPEED_UP_BUILD_RESPü"
CMD_UPGRADE_TECHNOLOGY_REQ†" 
CMD_UPGRADE_TECHNOLOGY_RESP°"
CMD_GET_TECHNOLOGY_REQ¢"
CMD_GET_TECHNOLOGY_RESP£" 
CMD_SPEED_UP_TECHNOLOGY_REQ§"!
CMD_SPEED_UP_TECHNOLOGY_RESP•"
CMD_CREATE_EQUIP_REQÆ"
CMD_CREATE_EQUIP_RESPØ"
CMD_STRENGTH_EQUIP_REQ∞"
CMD_STRENGTH_EQUIP_RESP±"
CMD_SHIP_BREAK_REQ≤"
CMD_SHIP_BREAK_RESP≥"
CMD_RESOLVE_EQUIP_REQ¥"
CMD_RESOLVE_EQUIP_RESPµ"
CMD_SHIP_ADD_EXP_REQ∂"
CMD_SHIP_ADD_EXP_RESP∑"
CMD_RESOLVE_BLUEPRINT_REQ∏"
CMD_RESOLVE_BLUEPRINT_RESPπ" 
CMD_SHIP_ADD_ENERGY_EXP_REQ¿"!
CMD_SHIP_ADD_ENERGY_EXP_RESP¡""
CMD_SHIP_LOCK_ENERGY_TIME_REQ¬"#
CMD_SHIP_LOCK_ENERGY_TIME_RESP√"
CMD_EQUIP_LEVELUP_REQ–"
CMD_EQUIP_LEVELUP_RESP—"
CMD_EQUIP_STARUP_REQ“"
CMD_EQUIP_STARUP_RESP”"
CMD_EQUIP_PURIFY_REQ‘"
CMD_EQUIP_PURIFY_RESP’"
CMD_EQUIP_REFINE_REQ÷"
CMD_EQUIP_REFINE_RESP◊"
CMD_EQUIP_RECOIN_REQÿ"
CMD_EQUIP_RECOIN_RESPŸ"
CMD_EQUIP_ENCHASE_REQ⁄"
CMD_EQUIP_ENCHASE_RESP€"
CMD_GEM_EQUIP_REQ‡"
CMD_GEM_EQUIP_RESP·"
CMD_GEM_MIX_REQ‚"
CMD_GEM_MIX_RESP„"
CMD_MIJI_MIX_REQÊ"
CMD_MIJI_MIX_RESPÁ"
CMD_MIJI_EQUIP_REQË"
CMD_MIJI_EQUIP_RESPÈ"
CMD_MIJI_LEVELUP_REQÍ"
CMD_MIJI_LEVELUP_RESPÎ"
CMD_MIJI_JINJIE_REQÏ"
CMD_MIJI_JINJIE_RESPÌ"
CMD_SKILL_LEVELUP_REQ 
CMD_SKILL_LEVELUP_RESPÒ 
CMD_OPEN_BOOK_REQÚ 
CMD_OPEN_BOOK_RESPÛ 
CMD_BOOK_LEVELUP_REQÙ 
CMD_BOOK_LEVELUP_RESPı 
CMD_OPEN_LOVER_REQˆ 
CMD_OPEN_LOVER_RESP˜ 
CMD_LOVER_LEVELUP_REQ¯ 
CMD_LOVER_LEVELUP_RESP˘ 
CMD_MONEY2GOLD_REQ˙ 
CMD_MONEY2GOLD_RESP˚ 
CMD_MONEY2HP_REQ¸ 
CMD_MONEY2HP_RESP˝ 
CMD_SHIP_LOTTERY_REQ˛ 
CMD_SHIP_LOTTERY_RESPˇ 
CMD_GET_TASK_LIST_REQÄ!
CMD_GET_TASK_LIST_RESPÅ!
CMD_GET_TASK_REWARD_REQÇ!
CMD_GET_TASK_REWARD_RESPÉ!
CMD_PVE_REQÄ$
CMD_PVE_RESPÅ$
CMD_PVE_GET_REWARD_REQê$
CMD_PVE_GET_REWARD_RESPë$
CMD_PVE_WATCH_SHOW_REQí$
CMD_PVE_WATCH_SHOW_RESPì$
CMD_PVE_CLEAR_REQî$
CMD_PVE_CLEAR_RESPï$
CMD_PVE_RESET_JINGYING_REQñ$ 
CMD_PVE_RESET_JINGYING_RESPó$
CMD_SPECIAL_STAGE_REQò$
CMD_SPECIAL_STAGE_RESPô$
CMD_PVE2_RESET_REQ–$
CMD_PVE2_RESET_RESP—$
CMD_PVE2_GET_ENEMY_REQ“$
CMD_PVE2_GET_ENEMY_RESP”$
CMD_PVE2_SET_ZHENXING_REQ‘$
CMD_PVE2_SET_ZHENXING_RESP’$
CMD_PVE2_FIGHT_REQ÷$
CMD_PVE2_FIGHT_RESP◊$
CMD_PVE2_GET_REWARD_REQÿ$
CMD_PVE2_GET_REWARD_RESPŸ$
CMD_PVE2_SELECT_BUFF_REQ⁄$
CMD_PVE2_SELECT_BUFF_RESP€$
CMD_PVE2_REFLESH_SHOP_REQ‹$
CMD_PVE2_REFLESH_SHOP_RESP›$
CMD_PVE2_SHOPPING_REQﬁ$
CMD_PVE2_SHOPPING_RESPﬂ$"
CMD_KNIGHT_REFLEASH_LOCK_RESP‡$
CMD_TRIAL_GET_REWARD_REQÙ$
CMD_TRIAL_GET_REWARD_RESPı$
CMD_TRIAL_ADD_TICKET_REQˆ$
CMD_TRIAL_ADD_TICKET_RESP˜$
CMD_TRIAL_GET_TIMES_REQ¯$
CMD_TRIAL_GET_TIMES_RESP˘$
CMD_TRIAL_OPEN_ATEA_REQÄ%
CMD_TRIAL_OPEN_ATEA_RESPÅ%$
CMD_TRIAL_GET_BUILDING_INFO_REQÇ%%
 CMD_TRIAL_GET_BUILDING_INFO_RESPÉ%
CMD_TRIAL_PVE_START_REQÑ%
CMD_TRIAL_PVE_START_RESPÖ%
CMD_TRIAL_PVE_END_REQÜ%
CMD_TRIAL_PVE_END_RESPá%
CMD_RANK_REQÄ&
CMD_RANK_RESPÅ&
CMD_ARENA_INFO_REQ†&
CMD_ARENA_INFO_RESP°&
CMD_ARENA_CHALLENGE_REQ¢&
CMD_ARENA_CHALLENGE_RESP£&
CMD_ARENA_TIMES_REQ§&
CMD_ARENA_TIMES_RESP•&#
CMD_ARENA_GET_DAILY_REWARD_REQ¶&$
CMD_ARENA_GET_DAILY_REWARD_RESPß&
CMD_ARENA_TITLE_REQ®&
CMD_ARENA_TITLE_RESP©& 
CMD_WBOSS_USER_INFO_GET_REQ–&!
CMD_WBOSS_USER_INFO_GET_RESP—&'
"CMD_WBOSS_GET_RANK_REWARD_LIST_REQ“&(
#CMD_WBOSS_GET_RANK_REWARD_LIST_RESP”&
CMD_WBOSS_ATTACK_REQ‘&
CMD_WBOSS_ATTACK_RESP’&
CMD_WBOSS_RANK_REQ÷&
CMD_WBOSS_RANK_RESP◊&
CMD_WLZB_REG_REQ‡&
CMD_WLZB_REG_RESP·&
CMD_WLZB_RCD_REQ‚&
CMD_WLZB_RCD_RESP„& 
CMD_WLZB_GET_FIGHT_INFO_REQ‰&!
CMD_WLZB_GET_FIGHT_INFO_RESPÂ&
CMD_WLZB_REWARD_REQÊ&
CMD_WLZB_REWARD_RESPÁ&!
CMD_WLZB_GET_REWARD_LIST_REQË&"
CMD_WLZB_GET_REWARD_LIST_RESPÈ&
CMD_MAIL_LIST_UPDATEˇ'
CMD_GET_MAIL_LIST_REQÄ(
CMD_GET_MAIL_LIST_RESPÅ(
CMD_READ_MAIL_REQÇ(
CMD_READ_MAIL_RESPÉ(
CMD_DEL_MAIL_REQÑ(
CMD_DEL_MAIL_RESPÖ(
CMD_SEND_MAIL_REQÜ(
CMD_SEND_MAIL_RESPá(
CMD_READ_MAIL_LIST_REQà(
CMD_READ_MAIL_LIST_RESPâ(
CMD_GET_FRIENDS_INFO_REQû(
CMD_GET_FRIENDS_INFO_RESPü(
CMD_APPLY_FRIEND_REQ†(
CMD_APPLY_FRIEND_RESP°(
CMD_ACCEPT_FRIEND_REQ¢(
CMD_ACCEPT_FRIEND_RESP£(
CMD_FRIEND_APPLY_UPDATE§(
CMD_BE_FRIEND_UPDATE•(
CMD_REMOVE_FRIEND_REQ¶(
CMD_REMOVE_FRIEND_RESPß(
CMD_BLACK_LIST_REQ®(
CMD_BLACK_LIST_RESP©(
CMD_TALK_LIST_REQ∞(
CMD_TALK_LIST_RESP±(
CMD_FRIEND_ADD_TILI_REQ≤(
CMD_FRIEND_ADD_TILI_RESP≥(
CMD_FRIEND_READ_TILI_REQ¥(
CMD_FRIEND_READ_TILI_RESPµ(
CMD_FRIEND_TILI_UPDATE∂(
CMD_GET_ACTIVITY_LIST_REQ–(
CMD_GET_ACTIVITY_LIST_RESP—(
CMD_ACTIVITY_CHANGE_REQ“(
CMD_ACTIVITY_CHANGE_RESP”(
CMD_ACTIVITY_SIGN_IN_REQ‘(
CMD_ACTIVITY_SIGN_IN_RESP’($
CMD_ACTIVITY_FIRST_RECHARGE_REQ÷(%
 CMD_ACTIVITY_FIRST_RECHARGE_RESP◊(
CMD_ACTIVITY_RECHARGE_REQÿ(
CMD_ACTIVITY_RECHARGE_RESPŸ(#
CMD_ACTIVITY_CREDIT_RETURN_REQ⁄($
CMD_ACTIVITY_CREDIT_RETURN_RESP€(
CMD_ACTIVITY_CONSUME_REQ‹(
CMD_ACTIVITY_CONSUME_RESP›( 
CMD_ACTIVITY_SEVEN_DAYS_REQﬁ(!
CMD_ACTIVITY_SEVEN_DAYS_RESPﬂ(
CMD_ACTIVITY_ONLINE_REQ‡(
CMD_ACTIVITY_ONLINE_RESP·(
CMD_ACTIVITY_POWER_REQ‚(
CMD_ACTIVITY_POWER_RESP„(!
CMD_ACTIVITY_GROWTH_FUND_REQ‰("
CMD_ACTIVITY_GROWTH_FUND_RESPÂ(
CMD_ACTIVITY_INVEST_REQÊ(
CMD_ACTIVITY_INVEST_RESPÁ(!
CMD_ACTIVITY_CHANGE_SHIP_REQË("
CMD_ACTIVITY_CHANGE_SHIP_RESPÈ( 
CMD_ACTIVITY_MONTH_SIGN_REQÍ(!
CMD_ACTIVITY_MONTH_SIGN_RESPÎ(
CMD_ACTIVITY_VIP_PACK_REQÏ(
CMD_ACTIVITY_VIP_PACK_RESPÌ(
CMD_ACTIVITY_EVERYDAY_REQ(
CMD_ACTIVITY_EVERYDAY_RESPÒ(
CMD_ACTIVITY_TURNTABLE_REQÚ( 
CMD_ACTIVITY_TURNTABLE_RESPÛ($
CMD_ACTIVITY_ADVANCED_MONEY_REQÙ(%
 CMD_ACTIVITY_ADVANCED_MONEY_RESPı(#
CMD_ACTIVITY_EXCHANGE_ITEM_REQˆ($
CMD_ACTIVITY_EXCHANGE_ITEM_RESP˜(
CMD_CHAT_REQû*
CMD_CHAT_RESPü*
CMD_CHAT_MSG°*
CMD_GET_CHAT_LOG_REQ§*
CMD_GET_CHAT_LOG_RESP•*
CMD_CDKEY_REQ®*
CMD_CDKEY_RESP©*
CMD_CJSZ_EXCNANGE_LIST_REQ∞* 
CMD_CJSZ_EXCNANGE_LIST_RESP±*
CMD_LEIJI_CHONGZHI_REQ≤*
CMD_LEIJI_CHONGZHI_RESP≥*
CMD_DANBI_CHONGZHI_REQ¥*
CMD_DANBI_CHONGZHI_RESPµ*
CMD_LOGIN_HUODONG_REQ∂*
CMD_LOGIN_HUODONG_RESP∑*
CMD_XIAOFEI_REQ∏*
CMD_XIAOFEI_RESPπ*"
CMD_LEIJI_CHONGZHI_REWARD_REQ∫*#
CMD_LEIJI_CHONGZHI_REWARD_RESPª*"
CMD_DANBI_CHONGZHI_REWARD_REQº*#
CMD_DANBI_CHONGZHI_REWARD_RESPΩ*
CMD_LOGIN_REWARD_REQæ*
CMD_LOGIN_REWARD_RESPø*
CMD_XIAOFEI_REWARD_REQ¿*
CMD_XIAOFEI_REWARD_RESP¡*
CMD_NEW_LEVEL_REQ¬*
CMD_NEW_LEVEL_RESP√*
CMD_NEW_LEVEL_REWARD_REQƒ*
CMD_NEW_LEVEL_REWARD_RESP≈*
CMD_DUIHUAN_INFO_REQ∆*
CMD_DUIHUAN_INFO_RESP«*
CMD_DUIHUAN_REQ»*
CMD_DUIHUAN_RESP…*
CMD_LEIJI_XIAOFEI_REQ *
CMD_LEIJI_XIAOFEI_RESPÀ*!
CMD_LEIJI_XIAOFEI_REWARD_REQÃ*"
CMD_LEIJI_XIAOFEI_REWARD_RESPÕ*
CMD_HUODONG_LIST_REQ–*
CMD_HUODONG_LIST_RESP—*
CMD_GET_RECHARGE_LIST_REQ“*
CMD_GET_RECHARGE_LIST_RESP”*
CMD_GET_TOP_ACT_REQ‘*
CMD_GET_TOP_ACT_RESP’*
CMD_CREATE_GROUP_REQÄ,
CMD_CREATE_GROUP_RESPÅ,
CMD_GET_GROUP_REQÇ,
CMD_GET_GROUP_RESPÉ,
CMD_GROUP_CONTRIBUTE_REQÑ,
CMD_GROUP_CONTRIBUTE_RESPÖ,
CMD_GROUP_LEVELUP_REQÜ,
CMD_GROUP_LEVELUP_RESPá,
CMD_GROUP_TECH_LEVELUP_REQà, 
CMD_GROUP_TECH_LEVELUP_RESPâ,
CMD_GROUP_GET_TECH_REQä,
CMD_GROUP_GET_TECH_RESPã,!
CMD_GROUP_JOIN_CONDITION_REQå,"
CMD_GROUP_JOIN_CONDITION_RESPç,
CMD_GROUP_JOIN_REQé,
CMD_GROUP_JOIN_RESPè,
CMD_GROUP_ALLOW_REQê,
CMD_GROUP_ALLOW_RESPë,
CMD_GROUP_EXIT_REQí,
CMD_GROUP_EXIT_RESPì,
CMD_GROUP_KICK_REQî,
CMD_GROUP_KICK_RESPï,
CMD_GROUP_JOB_REQñ,
CMD_GROUP_JOB_RESPó,
CMD_GROUP_DISBAND_REQò,
CMD_GROUP_DISBAND_RESPô,
CMD_GROUP_SEARCH_REQö,
CMD_GROUP_SEARCH_RESPõ,
CMD_GROUP_SHOP_REFRESH_REQú, 
CMD_GROUP_SHOP_REFRESH_RESPù,
CMD_GROUP_SHOPPING_REQû,
CMD_GROUP_SHOPPING_RESPü,
CMD_GROUP_BROADCAST_REQ†,
CMD_GROUP_BROADCAST_RESP°, 
CMD_GROUP_CONTRIBUTE_CD_REQ¢,!
CMD_GROUP_CONTRIBUTE_CD_RESP£,
CMD_GROUP_HELP_LIST_REQ§,
CMD_GROUP_HELP_LIST_RESP•,
CMD_GROUP_REQUEST_HELP_REQ¶, 
CMD_GROUP_REQUEST_HELP_RESPß,
CMD_GROUP_HELP_REQ®,
CMD_GROUP_HELP_RESP©,
CMD_GROUP_PVE_GET_INFO_REQ∞, 
CMD_GROUP_PVE_GET_INFO_RESP±,
CMD_GROUP_PVE_REQ≤,
CMD_GROUP_PVE_RESP≥,
CMD_GROUP_PVE_OK_REQ¥,
CMD_GROUP_PVE_OK_RESPµ, 
CMD_GROUP_PVE_ADD_TIMES_REQ∂,!
CMD_GROUP_PVE_ADD_TIMES_RESP∑,!
CMD_GROUP_PVE_GET_REWARD_REQ∏,"
CMD_GROUP_PVE_GET_REWARD_RESPπ,
CMD_GROUP_INVITE_REQ¿,
CMD_GROUP_INVITE_RESP¡,
CMD_GROUP_WORSHIP_REQ¬,
CMD_GROUP_WORSHIP_RESP√,
CMD_SDK_PAY_CALLBACK¸-
CMD_USER_SYNC_UPDATE˝-
CMD_NEW_GROUP_UPDATE˛-
CMD_GROUP_UPDATEˇ-
CMD_MPZ_GET_REQÄ.
CMD_MPZ_GET_RESPÅ.
CMD_MPZ_GET_RCD_REQÇ.
CMD_MPZ_GET_RCD_RESPÉ.
CMD_MPZ_MASTER_REG_REQÑ.
CMD_MPZ_MASTER_REG_RESPÖ.
CMD_MPZ_MEM_REG_REQÜ.
CMD_MPZ_MEM_REG_RESPá.
CMD_TIANJI_GET_REQê.
CMD_TIANJI_GET_RESPë.
CMD_TIANJI_REQí.
CMD_TIANJI_RESPì.
CMD_TIANJI_REWARD_REQî.
CMD_TIANJI_REWARD_RESPï.
CMD_TIANJI_REWARD_INFO_REQñ. 
CMD_TIANJI_REWARD_INFO_RESPó.
CMD_SHOP_BUY_REQö.
CMD_SHOP_BUY_RESPõ. 
CMD_SHOP_TIME_ITEM_LIST_REQú.!
CMD_SHOP_TIME_ITEM_LIST_RESPù.
CMD_UPDATE_SLAVE_DATAØ.
CMD_SLAVE_SYNC_DATA_REQ∞.
CMD_SLAVE_SYNC_DATA_RESP±.
CMD_SLAVE_GET_RES_REQ≤.
CMD_SLAVE_GET_RES_RESP≥.
CMD_SLAVE_FREE_REQ¥.
CMD_SLAVE_FREE_RESPµ.
CMD_SLAVE_SHOW_REQ∂.
CMD_SLAVE_SHOW_RESP∑.
CMD_SLAVE_WORK_REQ∏.
CMD_SLAVE_WORK_RESPπ.
CMD_SLAVE_FAWN_ON_REQ∫.
CMD_SLAVE_FAWN_ON_RESPª.
CMD_SLAVE_HELP_REQº.
CMD_SLAVE_HELP_RESPΩ.
CMD_SLAVE_SEARCH_REQæ.
CMD_SLAVE_SEARCH_RESPø.
CMD_SLAVE_ADD_TIMES_REQ¿.
CMD_SLAVE_ADD_TIMES_RESP¡.
CMD_SLAVE_ATTACK_REQ¬.
CMD_SLAVE_ATTACK_RESP√.
CMD_BUILDING_UPGRADE_REQ∞0
CMD_BUILDING_UPGRADE_RESP±0
CMD_BUILDING_UPDATE_REQ≤0
CMD_BUILDING_UPDATE_RESP≥0&
!CMD_BUILDING_UPGRADE_SPEED_UP_REQ¥0'
"CMD_BUILDING_UPGRADE_SPEED_UP_RESPµ0
CMD_BUILD_QUEUE_ADD_REQ∂0
CMD_BUILD_QUEUE_ADD_RESP∑0
CMD_BUILD_QUEUE_REMOVE_REQ∏0 
CMD_BUILD_QUEUE_REMOVE_RESPπ0
CMD_ADD_MONEY_CALLBACKÄ2
CMD_CDKEY_INNER_REQÇ2
CMD_CDKEY_INNER_RESPÉ2
CMD_TEST_ADD_MONEY_REQˇ1%
 CMD_GET_OTHER_USER_INFO_LIST_REQ˙3&
!CMD_GET_OTHER_USER_INFO_LIST_RESP˚3 
CMD_GET_OTHER_USER_INFO_REQ¸3!
CMD_GET_OTHER_USER_INFO_RESP˝3
CMD_CLIENT_GM_REQ˛3
CMD_CLIENT_GM_RESPˇ3 
CMD_HTTPCB_GM_FIGHT_SIM_REQÄ@!
CMD_HTTPCB_GM_FIGHT_SIM_RESPÅ@
CMD_HTTPCB_GM_ADD_ITEM_REQÇ@ 
CMD_HTTPCB_GM_ADD_ITEM_RESPÉ@
CMD_HTTPCB_GM_BLOCK_REQÑ@
CMD_HTTPCB_GM_BLOCK_RESPÖ@
CMD_MULTICASTÄB