#!/usr/bin/perl 


my @keyroot = qw(2 3 4 5 6 7 8 9 A B C D E F G H J K M N P Q R S T U V W X Y Z);
my $len = scalar(@keyroot);
for(my $i = 1; $i <= 10; $i++)
{
	my $ch = @keyroot[$i-1];
	`./cdkeygen 2 $i 50000 1 GT$ch`;
}
