local IVESTGROUP = {}
IVESTGROUP["index"] = {}
IVESTGROUP["index"][1] = 1
IVESTGROUP[1] = {}
	IVESTGROUP[1]["ID"] = 1
	IVESTGROUP[1]["PICTURE"] = 100
	IVESTGROUP[1]["TIME"] = 10
	IVESTGROUP[1]["EARNING"] = {}
		IVESTGROUP[1]["EARNING"][1] = 10
		IVESTGROUP[1]["EARNING"][2] = 15
	IVESTGROUP[1]["WEIGHT"] = 1
	IVESTGROUP[1]["real_idx"] = 1

IVESTGROUP["index"][2] = 2
IVESTGROUP[2] = {}
	IVESTGROUP[2]["ID"] = 2
	IVESTGROUP[2]["PICTURE"] = 500
	IVESTGROUP[2]["TIME"] = 30
	IVESTGROUP[2]["EARNING"] = {}
		IVESTGROUP[2]["EARNING"][1] = 10
		IVESTGROUP[2]["EARNING"][2] = 40
	IVESTGROUP[2]["WEIGHT"] = 1
	IVESTGROUP[2]["real_idx"] = 2

IVESTGROUP["index"][3] = 3
IVESTGROUP[3] = {}
	IVESTGROUP[3]["ID"] = 3
	IVESTGROUP[3]["PICTURE"] = 1000
	IVESTGROUP[3]["TIME"] = 60
	IVESTGROUP[3]["EARNING"] = {}
		IVESTGROUP[3]["EARNING"][1] = 10
		IVESTGROUP[3]["EARNING"][2] = 30
	IVESTGROUP[3]["WEIGHT"] = 1
	IVESTGROUP[3]["real_idx"] = 3

IVESTGROUP["index"][4] = 4
IVESTGROUP[4] = {}
	IVESTGROUP[4]["ID"] = 4
	IVESTGROUP[4]["PICTURE"] = 3000
	IVESTGROUP[4]["TIME"] = 90
	IVESTGROUP[4]["EARNING"] = {}
		IVESTGROUP[4]["EARNING"][1] = 5
		IVESTGROUP[4]["EARNING"][2] = 25
	IVESTGROUP[4]["WEIGHT"] = 1
	IVESTGROUP[4]["real_idx"] = 4

IVESTGROUP["index"][5] = 5
IVESTGROUP[5] = {}
	IVESTGROUP[5]["ID"] = 5
	IVESTGROUP[5]["PICTURE"] = 5000
	IVESTGROUP[5]["TIME"] = 120
	IVESTGROUP[5]["EARNING"] = {}
		IVESTGROUP[5]["EARNING"][1] = 5
		IVESTGROUP[5]["EARNING"][2] = 20
	IVESTGROUP[5]["WEIGHT"] = 1
	IVESTGROUP[5]["real_idx"] = 5


IVESTGROUP["len"] = 5

return IVESTGROUP
