local ARENA_STORE = {}
ARENA_STORE["index"] = {}
ARENA_STORE["index"][1] = 1
ARENA_STORE[1] = {}
	ARENA_STORE[1]["ID"] = 1
	ARENA_STORE[1]["ITEM_ID"] = 11001
	ARENA_STORE[1]["ITEM_NUM"] = 1
	ARENA_STORE[1]["HOMOR"] = 150
	ARENA_STORE[1]["TODAY_BUY"] = 0
	ARENA_STORE[1]["ALL_BUY"] = 0
	ARENA_STORE[1]["real_idx"] = 1

ARENA_STORE["index"][2] = 2
ARENA_STORE[2] = {}
	ARENA_STORE[2]["ID"] = 2
	ARENA_STORE[2]["ITEM_ID"] = 3001
	ARENA_STORE[2]["ITEM_NUM"] = 500
	ARENA_STORE[2]["HOMOR"] = 10
	ARENA_STORE[2]["TODAY_BUY"] = 0
	ARENA_STORE[2]["ALL_BUY"] = 0
	ARENA_STORE[2]["real_idx"] = 2

ARENA_STORE["index"][3] = 3
ARENA_STORE[3] = {}
	ARENA_STORE[3]["ID"] = 3
	ARENA_STORE[3]["ITEM_ID"] = 4001
	ARENA_STORE[3]["ITEM_NUM"] = 1000
	ARENA_STORE[3]["HOMOR"] = 5
	ARENA_STORE[3]["TODAY_BUY"] = 0
	ARENA_STORE[3]["ALL_BUY"] = 0
	ARENA_STORE[3]["real_idx"] = 3

ARENA_STORE["index"][4] = 4
ARENA_STORE[4] = {}
	ARENA_STORE[4]["ID"] = 4
	ARENA_STORE[4]["ITEM_ID"] = 5001
	ARENA_STORE[4]["ITEM_NUM"] = 1000
	ARENA_STORE[4]["HOMOR"] = 20
	ARENA_STORE[4]["TODAY_BUY"] = 0
	ARENA_STORE[4]["ALL_BUY"] = 0
	ARENA_STORE[4]["real_idx"] = 4

ARENA_STORE["index"][5] = 5
ARENA_STORE[5] = {}
	ARENA_STORE[5]["ID"] = 5
	ARENA_STORE[5]["ITEM_ID"] = 6001
	ARENA_STORE[5]["ITEM_NUM"] = 1000
	ARENA_STORE[5]["HOMOR"] = 100
	ARENA_STORE[5]["TODAY_BUY"] = 0
	ARENA_STORE[5]["ALL_BUY"] = 0
	ARENA_STORE[5]["real_idx"] = 5


ARENA_STORE["len"] = 5

return ARENA_STORE
