local CREDITRETURN = {}
CREDITRETURN["index"] = {}
CREDITRETURN["index"][1] = 1
CREDITRETURN[1] = {}
	CREDITRETURN[1]["ID"] = 1
	CREDITRETURN[1]["INPUT"] = 50
	CREDITRETURN[1]["OUTPUT"] = {}
		CREDITRETURN[1]["OUTPUT"][1] = 70
		CREDITRETURN[1]["OUTPUT"][2] = 100
	CREDITRETURN[1]["real_idx"] = 1

CREDITRETURN["index"][2] = 2
CREDITRETURN[2] = {}
	CREDITRETURN[2]["ID"] = 2
	CREDITRETURN[2]["INPUT"] = 100
	CREDITRETURN[2]["OUTPUT"] = {}
		CREDITRETURN[2]["OUTPUT"][1] = 110
		CREDITRETURN[2]["OUTPUT"][2] = 200
	CREDITRETURN[2]["real_idx"] = 2

CREDITRETURN["index"][3] = 3
CREDITRETURN[3] = {}
	CREDITRETURN[3]["ID"] = 3
	CREDITRETURN[3]["INPUT"] = 500
	CREDITRETURN[3]["OUTPUT"] = {}
		CREDITRETURN[3]["OUTPUT"][1] = 560
		CREDITRETURN[3]["OUTPUT"][2] = 800
	CREDITRETURN[3]["real_idx"] = 3

CREDITRETURN["index"][4] = 4
CREDITRETURN[4] = {}
	CREDITRETURN[4]["ID"] = 4
	CREDITRETURN[4]["INPUT"] = 1500
	CREDITRETURN[4]["OUTPUT"] = {}
		CREDITRETURN[4]["OUTPUT"][1] = 1700
		CREDITRETURN[4]["OUTPUT"][2] = 2000
	CREDITRETURN[4]["real_idx"] = 4

CREDITRETURN["index"][5] = 5
CREDITRETURN[5] = {}
	CREDITRETURN[5]["ID"] = 5
	CREDITRETURN[5]["INPUT"] = 3000
	CREDITRETURN[5]["OUTPUT"] = {}
		CREDITRETURN[5]["OUTPUT"][1] = 3800
		CREDITRETURN[5]["OUTPUT"][2] = 5000
	CREDITRETURN[5]["real_idx"] = 5


CREDITRETURN["len"] = 5

return CREDITRETURN
