local GROUP_TASK = {}
GROUP_TASK["index"] = {}
GROUP_TASK["index"][1] = 1
GROUP_TASK[1] = {}
	GROUP_TASK[1]["GTASK_ID"] = 1
	GROUP_TASK[1]["GTASK_TYPE"] = 1
	GROUP_TASK[1]["KEY"] = 1
	GROUP_TASK[1]["QUAN_1"] = 2
	GROUP_TASK[1]["REWARD_ID1"] = 10001
	GROUP_TASK[1]["REWARD_QUAN_1"] = 5
	GROUP_TASK[1]["QUAN_2"] = 0
	GROUP_TASK[1]["REWARD_ID2"] = 0
	GROUP_TASK[1]["REWARD_QUAN_2"] = 0
	GROUP_TASK[1]["QUAN_3"] = 0
	GROUP_TASK[1]["REWARD_ID3"] = 0
	GROUP_TASK[1]["REWARD_QUAN_3"] = 0
	GROUP_TASK[1]["real_idx"] = 1

GROUP_TASK["index"][2] = 2
GROUP_TASK[2] = {}
	GROUP_TASK[2]["GTASK_ID"] = 2
	GROUP_TASK[2]["GTASK_TYPE"] = 2
	GROUP_TASK[2]["KEY"] = 2
	GROUP_TASK[2]["QUAN_1"] = 0
	GROUP_TASK[2]["REWARD_ID1"] = 0
	GROUP_TASK[2]["REWARD_QUAN_1"] = 0
	GROUP_TASK[2]["QUAN_2"] = 2
	GROUP_TASK[2]["REWARD_ID2"] = 10001
	GROUP_TASK[2]["REWARD_QUAN_2"] = 10
	GROUP_TASK[2]["QUAN_3"] = 0
	GROUP_TASK[2]["REWARD_ID3"] = 0
	GROUP_TASK[2]["REWARD_QUAN_3"] = 0
	GROUP_TASK[2]["real_idx"] = 2

GROUP_TASK["index"][3] = 3
GROUP_TASK[3] = {}
	GROUP_TASK[3]["GTASK_ID"] = 3
	GROUP_TASK[3]["GTASK_TYPE"] = 3
	GROUP_TASK[3]["KEY"] = 3
	GROUP_TASK[3]["QUAN_1"] = 0
	GROUP_TASK[3]["REWARD_ID1"] = 0
	GROUP_TASK[3]["REWARD_QUAN_1"] = 0
	GROUP_TASK[3]["QUAN_2"] = 0
	GROUP_TASK[3]["REWARD_ID2"] = 0
	GROUP_TASK[3]["REWARD_QUAN_2"] = 0
	GROUP_TASK[3]["QUAN_3"] = 10
	GROUP_TASK[3]["REWARD_ID3"] = 10001
	GROUP_TASK[3]["REWARD_QUAN_3"] = 15
	GROUP_TASK[3]["real_idx"] = 3


GROUP_TASK["len"] = 3

return GROUP_TASK
