local RECHARGE_GIFT_BAG = {}
RECHARGE_GIFT_BAG["index"] = {}
RECHARGE_GIFT_BAG["index"][1] = 1
RECHARGE_GIFT_BAG[1] = {}
	RECHARGE_GIFT_BAG[1]["ID"] = 1
	RECHARGE_GIFT_BAG[1]["COST"] = 6
	RECHARGE_GIFT_BAG[1]["DAY"] = 1
	RECHARGE_GIFT_BAG[1]["ITEM"] = {}
		RECHARGE_GIFT_BAG[1]["ITEM"][1] = 11001
		RECHARGE_GIFT_BAG[1]["ITEM"][2] = 13005
		RECHARGE_GIFT_BAG[1]["ITEM"][3] = 4001
		RECHARGE_GIFT_BAG[1]["ITEM"][4] = 5001
	RECHARGE_GIFT_BAG[1]["NUM"] = {}
		RECHARGE_GIFT_BAG[1]["NUM"][1] = 20
		RECHARGE_GIFT_BAG[1]["NUM"][2] = 60
		RECHARGE_GIFT_BAG[1]["NUM"][3] = 6000
		RECHARGE_GIFT_BAG[1]["NUM"][4] = 6000
	RECHARGE_GIFT_BAG[1]["real_idx"] = 1

RECHARGE_GIFT_BAG["index"][2] = 2
RECHARGE_GIFT_BAG[2] = {}
	RECHARGE_GIFT_BAG[2]["ID"] = 2
	RECHARGE_GIFT_BAG[2]["COST"] = 18
	RECHARGE_GIFT_BAG[2]["DAY"] = 3
	RECHARGE_GIFT_BAG[2]["ITEM"] = {}
		RECHARGE_GIFT_BAG[2]["ITEM"][1] = 11001
		RECHARGE_GIFT_BAG[2]["ITEM"][2] = 13003
		RECHARGE_GIFT_BAG[2]["ITEM"][3] = 16002
		RECHARGE_GIFT_BAG[2]["ITEM"][4] = 13005
		RECHARGE_GIFT_BAG[2]["ITEM"][5] = 11105
	RECHARGE_GIFT_BAG[2]["NUM"] = {}
		RECHARGE_GIFT_BAG[2]["NUM"][1] = 45
		RECHARGE_GIFT_BAG[2]["NUM"][2] = 4
		RECHARGE_GIFT_BAG[2]["NUM"][3] = 1
		RECHARGE_GIFT_BAG[2]["NUM"][4] = 130
		RECHARGE_GIFT_BAG[2]["NUM"][5] = 1
	RECHARGE_GIFT_BAG[2]["real_idx"] = 2

RECHARGE_GIFT_BAG["index"][3] = 3
RECHARGE_GIFT_BAG[3] = {}
	RECHARGE_GIFT_BAG[3]["ID"] = 3
	RECHARGE_GIFT_BAG[3]["COST"] = 30
	RECHARGE_GIFT_BAG[3]["DAY"] = 5
	RECHARGE_GIFT_BAG[3]["ITEM"] = {}
		RECHARGE_GIFT_BAG[3]["ITEM"][1] = 902602
		RECHARGE_GIFT_BAG[3]["ITEM"][2] = 902902
		RECHARGE_GIFT_BAG[3]["ITEM"][3] = 902702
		RECHARGE_GIFT_BAG[3]["ITEM"][4] = 902802
		RECHARGE_GIFT_BAG[3]["ITEM"][5] = 11111
	RECHARGE_GIFT_BAG[3]["NUM"] = {}
		RECHARGE_GIFT_BAG[3]["NUM"][1] = 1
		RECHARGE_GIFT_BAG[3]["NUM"][2] = 1
		RECHARGE_GIFT_BAG[3]["NUM"][3] = 1
		RECHARGE_GIFT_BAG[3]["NUM"][4] = 1
		RECHARGE_GIFT_BAG[3]["NUM"][5] = 1
	RECHARGE_GIFT_BAG[3]["real_idx"] = 3


RECHARGE_GIFT_BAG["len"] = 3

return RECHARGE_GIFT_BAG
