local STRONG = {}
STRONG["index"] = {}
STRONG["index"][1] = 1
STRONG[1] = {}
	STRONG[1]["ID"] = 1
	STRONG[1]["TYPE"] = 5
	STRONG[1]["TAB"] = 1
	STRONG[1]["NAME"] = "strong name 1"
	STRONG[1]["SWITCHOVER"] = 2
	STRONG[1]["MEMO"] = ""
	STRONG[1]["CONDITION"] = ""
	STRONG[1]["FUNCTION_OPEN"] = "zzgf_open"
	STRONG[1]["BUILDING_NAME"] = "BuildingName_14"
	STRONG[1]["TURN_TYPE"] = 2
	STRONG[1]["TURN_ID"] = 12
	STRONG[1]["ICON"] = "icon_fcsx.png"
	STRONG[1]["ORDER"] = 1
	STRONG[1]["STRING"] = "go"
	STRONG[1]["STRING_2"] = "go"
	STRONG[1]["real_idx"] = 1

STRONG["index"][2] = 2
STRONG[2] = {}
	STRONG[2]["ID"] = 2
	STRONG[2]["TYPE"] = 5
	STRONG[2]["TAB"] = 1
	STRONG[2]["NAME"] = "strong name 2"
	STRONG[2]["SWITCHOVER"] = 1
	STRONG[2]["MEMO"] = "strong memo 2"
	STRONG[2]["CONDITION"] = ""
	STRONG[2]["FUNCTION_OPEN"] = ""
	STRONG[2]["BUILDING_NAME"] = ""
	STRONG[2]["TURN_TYPE"] = 16
	STRONG[2]["TURN_ID"] = 0
	STRONG[2]["ICON"] = "icon_zjszfc.png"
	STRONG[2]["ORDER"] = 2
	STRONG[2]["STRING"] = "go"
	STRONG[2]["STRING_2"] = "go"
	STRONG[2]["real_idx"] = 2

STRONG["index"][3] = 3
STRONG[3] = {}
	STRONG[3]["ID"] = 3
	STRONG[3]["TYPE"] = 5
	STRONG[3]["TAB"] = 1
	STRONG[3]["NAME"] = "strong name 3"
	STRONG[3]["SWITCHOVER"] = 1
	STRONG[3]["MEMO"] = "strong memo 3"
	STRONG[3]["CONDITION"] = ""
	STRONG[3]["FUNCTION_OPEN"] = ""
	STRONG[3]["BUILDING_NAME"] = ""
	STRONG[3]["TURN_TYPE"] = 16
	STRONG[3]["TURN_ID"] = 0
	STRONG[3]["ICON"] = "icon_hqfc.png"
	STRONG[3]["ORDER"] = 5
	STRONG[3]["STRING"] = "go"
	STRONG[3]["STRING_2"] = "go"
	STRONG[3]["real_idx"] = 3

STRONG["index"][4] = 4
STRONG[4] = {}
	STRONG[4]["ID"] = 4
	STRONG[4]["TYPE"] = 5
	STRONG[4]["TAB"] = 1
	STRONG[4]["NAME"] = "strong name 4"
	STRONG[4]["SWITCHOVER"] = 1
	STRONG[4]["MEMO"] = "strong memo 4"
	STRONG[4]["CONDITION"] = ""
	STRONG[4]["FUNCTION_OPEN"] = ""
	STRONG[4]["BUILDING_NAME"] = ""
	STRONG[4]["TURN_TYPE"] = 16
	STRONG[4]["TURN_ID"] = 0
	STRONG[4]["ICON"] = "icon_tsdj.png"
	STRONG[4]["ORDER"] = 4
	STRONG[4]["STRING"] = "go"
	STRONG[4]["STRING_2"] = "go"
	STRONG[4]["real_idx"] = 4

STRONG["index"][5] = 5
STRONG[5] = {}
	STRONG[5]["ID"] = 5
	STRONG[5]["TYPE"] = 5
	STRONG[5]["TAB"] = 1
	STRONG[5]["NAME"] = "strong name 5"
	STRONG[5]["SWITCHOVER"] = 1
	STRONG[5]["MEMO"] = "strong memo 5"
	STRONG[5]["CONDITION"] = ""
	STRONG[5]["FUNCTION_OPEN"] = "dzgc_open"
	STRONG[5]["BUILDING_NAME"] = "BuildingName_16"
	STRONG[5]["TURN_TYPE"] = 16
	STRONG[5]["TURN_ID"] = 0
	STRONG[5]["ICON"] = "icon_fctp.png"
	STRONG[5]["ORDER"] = 3
	STRONG[5]["STRING"] = "go"
	STRONG[5]["STRING_2"] = "go"
	STRONG[5]["real_idx"] = 5

STRONG["index"][6] = 6
STRONG[6] = {}
	STRONG[6]["ID"] = 6
	STRONG[6]["TYPE"] = 5
	STRONG[6]["TAB"] = 1
	STRONG[6]["NAME"] = "strong name 6"
	STRONG[6]["SWITCHOVER"] = 1
	STRONG[6]["MEMO"] = "strong memo 6"
	STRONG[6]["CONDITION"] = ""
	STRONG[6]["FUNCTION_OPEN"] = "wqyj_open"
	STRONG[6]["BUILDING_NAME"] = "BuildingName_4"
	STRONG[6]["TURN_TYPE"] = 16
	STRONG[6]["TURN_ID"] = 0
	STRONG[6]["ICON"] = "icon_zbcd.png"
	STRONG[6]["ORDER"] = 6
	STRONG[6]["STRING"] = "go"
	STRONG[6]["STRING_2"] = "go"
	STRONG[6]["real_idx"] = 6

STRONG["index"][7] = 7
STRONG[7] = {}
	STRONG[7]["ID"] = 7
	STRONG[7]["TYPE"] = 5
	STRONG[7]["TAB"] = 1
	STRONG[7]["NAME"] = "strong name 7"
	STRONG[7]["SWITCHOVER"] = 1
	STRONG[7]["MEMO"] = "strong memo 7"
	STRONG[7]["CONDITION"] = ""
	STRONG[7]["FUNCTION_OPEN"] = "wqyj_open"
	STRONG[7]["BUILDING_NAME"] = "BuildingName_4"
	STRONG[7]["TURN_TYPE"] = 2
	STRONG[7]["TURN_ID"] = 9
	STRONG[7]["ICON"] = "icon_zbqh.png"
	STRONG[7]["ORDER"] = 7
	STRONG[7]["STRING"] = "go"
	STRONG[7]["STRING_2"] = "go"
	STRONG[7]["real_idx"] = 7

STRONG["index"][8] = 8
STRONG[8] = {}
	STRONG[8]["ID"] = 8
	STRONG[8]["TYPE"] = 5
	STRONG[8]["TAB"] = 1
	STRONG[8]["NAME"] = "strong name 8"
	STRONG[8]["SWITCHOVER"] = 1
	STRONG[8]["MEMO"] = "strong memo 8"
	STRONG[8]["CONDITION"] = "gem_open"
	STRONG[8]["FUNCTION_OPEN"] = ""
	STRONG[8]["BUILDING_NAME"] = ""
	STRONG[8]["TURN_TYPE"] = 16
	STRONG[8]["TURN_ID"] = 0
	STRONG[8]["ICON"] = "icon_cdjn.png"
	STRONG[8]["ORDER"] = 8
	STRONG[8]["STRING"] = "go"
	STRONG[8]["STRING_2"] = "go"
	STRONG[8]["real_idx"] = 8

STRONG["index"][9] = 9
STRONG[9] = {}
	STRONG[9]["ID"] = 9
	STRONG[9]["TYPE"] = 5
	STRONG[9]["TAB"] = 1
	STRONG[9]["NAME"] = "strong name 9"
	STRONG[9]["SWITCHOVER"] = 1
	STRONG[9]["MEMO"] = "strong memo 9"
	STRONG[9]["CONDITION"] = "nlc_open"
	STRONG[9]["FUNCTION_OPEN"] = ""
	STRONG[9]["BUILDING_NAME"] = ""
	STRONG[9]["TURN_TYPE"] = 16
	STRONG[9]["TURN_ID"] = 0
	STRONG[9]["ICON"] = "icon_jnqh.png"
	STRONG[9]["ORDER"] = 9
	STRONG[9]["STRING"] = "go"
	STRONG[9]["STRING_2"] = "go"
	STRONG[9]["real_idx"] = 9

STRONG["index"][10] = 10
STRONG[10] = {}
	STRONG[10]["ID"] = 10
	STRONG[10]["TYPE"] = 5
	STRONG[10]["TAB"] = 2
	STRONG[10]["NAME"] = "strong name 10"
	STRONG[10]["SWITCHOVER"] = 1
	STRONG[10]["MEMO"] = "strong memo 10"
	STRONG[10]["CONDITION"] = "planet_open"
	STRONG[10]["FUNCTION_OPEN"] = ""
	STRONG[10]["BUILDING_NAME"] = ""
	STRONG[10]["TURN_TYPE"] = 18
	STRONG[10]["TURN_ID"] = 0
	STRONG[10]["ICON"] = "icon_bsxq.png"
	STRONG[10]["ORDER"] = 1
	STRONG[10]["STRING"] = "go"
	STRONG[10]["STRING_2"] = "go"
	STRONG[10]["real_idx"] = 10

STRONG["index"][11] = 11
STRONG[11] = {}
	STRONG[11]["ID"] = 11
	STRONG[11]["TYPE"] = 5
	STRONG[11]["TAB"] = 2
	STRONG[11]["NAME"] = "strong name 11"
	STRONG[11]["SWITCHOVER"] = 1
	STRONG[11]["MEMO"] = "strong memo 11"
	STRONG[11]["CONDITION"] = "league_open"
	STRONG[11]["FUNCTION_OPEN"] = ""
	STRONG[11]["BUILDING_NAME"] = ""
	STRONG[11]["TURN_TYPE"] = 21
	STRONG[11]["TURN_ID"] = 0
	STRONG[11]["ICON"] = "icon_tsdj.png"
	STRONG[11]["ORDER"] = 2
	STRONG[11]["STRING"] = "go"
	STRONG[11]["STRING_2"] = "join covenant"
	STRONG[11]["real_idx"] = 11

STRONG["index"][12] = 12
STRONG[12] = {}
	STRONG[12]["ID"] = 12
	STRONG[12]["TYPE"] = 5
	STRONG[12]["TAB"] = 2
	STRONG[12]["NAME"] = "BuildingName_6"
	STRONG[12]["SWITCHOVER"] = 1
	STRONG[12]["MEMO"] = "strong memo 12"
	STRONG[12]["CONDITION"] = ""
	STRONG[12]["FUNCTION_OPEN"] = ""
	STRONG[12]["BUILDING_NAME"] = ""
	STRONG[12]["TURN_TYPE"] = 3
	STRONG[12]["TURN_ID"] = 0
	STRONG[12]["ICON"] = "icon_tsdj.png"
	STRONG[12]["ORDER"] = 3
	STRONG[12]["STRING"] = "go"
	STRONG[12]["STRING_2"] = "go"
	STRONG[12]["real_idx"] = 12

STRONG["index"][13] = 13
STRONG[13] = {}
	STRONG[13]["ID"] = 13
	STRONG[13]["TYPE"] = 5
	STRONG[13]["TAB"] = 2
	STRONG[13]["NAME"] = "task"
	STRONG[13]["SWITCHOVER"] = 1
	STRONG[13]["MEMO"] = "strong memo 13"
	STRONG[13]["CONDITION"] = ""
	STRONG[13]["FUNCTION_OPEN"] = ""
	STRONG[13]["BUILDING_NAME"] = ""
	STRONG[13]["TURN_TYPE"] = 20
	STRONG[13]["TURN_ID"] = 0
	STRONG[13]["ICON"] = "icon_tsdj.png"
	STRONG[13]["ORDER"] = 5
	STRONG[13]["STRING"] = "go"
	STRONG[13]["STRING_2"] = "go"
	STRONG[13]["real_idx"] = 13

STRONG["index"][14] = 14
STRONG[14] = {}
	STRONG[14]["ID"] = 14
	STRONG[14]["TYPE"] = 5
	STRONG[14]["TAB"] = 2
	STRONG[14]["NAME"] = "shop"
	STRONG[14]["SWITCHOVER"] = 1
	STRONG[14]["MEMO"] = "strong memo 14"
	STRONG[14]["CONDITION"] = ""
	STRONG[14]["FUNCTION_OPEN"] = ""
	STRONG[14]["BUILDING_NAME"] = ""
	STRONG[14]["TURN_TYPE"] = 19
	STRONG[14]["TURN_ID"] = 0
	STRONG[14]["ICON"] = "icon_tsdj.png"
	STRONG[14]["ORDER"] = 4
	STRONG[14]["STRING"] = "go"
	STRONG[14]["STRING_2"] = "go"
	STRONG[14]["real_idx"] = 14

STRONG["index"][15] = 15
STRONG[15] = {}
	STRONG[15]["ID"] = 15
	STRONG[15]["TYPE"] = 5
	STRONG[15]["TAB"] = 2
	STRONG[15]["NAME"] = "BuildingName_9"
	STRONG[15]["SWITCHOVER"] = 1
	STRONG[15]["MEMO"] = "strong memo 15"
	STRONG[15]["CONDITION"] = ""
	STRONG[15]["FUNCTION_OPEN"] = ""
	STRONG[15]["BUILDING_NAME"] = ""
	STRONG[15]["TURN_TYPE"] = 1
	STRONG[15]["TURN_ID"] = ""
	STRONG[15]["ICON"] = "icon_txts.png"
	STRONG[15]["ORDER"] = 6
	STRONG[15]["STRING"] = "go"
	STRONG[15]["STRING_2"] = "go"
	STRONG[15]["real_idx"] = 15

STRONG["index"][16] = 16
STRONG[16] = {}
	STRONG[16]["ID"] = 16
	STRONG[16]["TYPE"] = 5
	STRONG[16]["TAB"] = ""
	STRONG[16]["NAME"] = "trial"
	STRONG[16]["SWITCHOVER"] = 1
	STRONG[16]["MEMO"] = "strong memo 16"
	STRONG[16]["CONDITION"] = "trial_open"
	STRONG[16]["FUNCTION_OPEN"] = ""
	STRONG[16]["BUILDING_NAME"] = ""
	STRONG[16]["TURN_TYPE"] = 12
	STRONG[16]["TURN_ID"] = 0
	STRONG[16]["ICON"] = "icon_txts.png"
	STRONG[16]["ORDER"] = 7
	STRONG[16]["STRING"] = "go"
	STRONG[16]["STRING_2"] = "go"
	STRONG[16]["real_idx"] = 16

STRONG["index"][17] = 17
STRONG[17] = {}
	STRONG[17]["ID"] = 17
	STRONG[17]["TYPE"] = 5
	STRONG[17]["TAB"] = 3
	STRONG[17]["NAME"] = "strong name 17"
	STRONG[17]["SWITCHOVER"] = 1
	STRONG[17]["MEMO"] = "strong memo 17"
	STRONG[17]["CONDITION"] = ""
	STRONG[17]["FUNCTION_OPEN"] = ""
	STRONG[17]["BUILDING_NAME"] = ""
	STRONG[17]["TURN_TYPE"] = 2
	STRONG[17]["TURN_ID"] = 10
	STRONG[17]["ICON"] = "icon_txts.png"
	STRONG[17]["ORDER"] = 1
	STRONG[17]["STRING"] = "go"
	STRONG[17]["STRING_2"] = "go"
	STRONG[17]["real_idx"] = 17

STRONG["index"][18] = 18
STRONG[18] = {}
	STRONG[18]["ID"] = 18
	STRONG[18]["TYPE"] = 5
	STRONG[18]["TAB"] = 3
	STRONG[18]["NAME"] = "strong name 18"
	STRONG[18]["SWITCHOVER"] = 1
	STRONG[18]["MEMO"] = "strong memo 18"
	STRONG[18]["CONDITION"] = "league_open"
	STRONG[18]["FUNCTION_OPEN"] = ""
	STRONG[18]["BUILDING_NAME"] = ""
	STRONG[18]["TURN_TYPE"] = 9
	STRONG[18]["TURN_ID"] = 0
	STRONG[18]["ICON"] = "icon_txts.png"
	STRONG[18]["ORDER"] = 2
	STRONG[18]["STRING"] = "go"
	STRONG[18]["STRING_2"] = "join covenant"
	STRONG[18]["real_idx"] = 18

STRONG["index"][19] = 19
STRONG[19] = {}
	STRONG[19]["ID"] = 19
	STRONG[19]["TYPE"] = 5
	STRONG[19]["TAB"] = 4
	STRONG[19]["NAME"] = "strong name 19"
	STRONG[19]["SWITCHOVER"] = 1
	STRONG[19]["MEMO"] = "strong memo 19"
	STRONG[19]["CONDITION"] = ""
	STRONG[19]["FUNCTION_OPEN"] = ""
	STRONG[19]["BUILDING_NAME"] = ""
	STRONG[19]["TURN_TYPE"] = 2
	STRONG[19]["TURN_ID"] = 11
	STRONG[19]["ICON"] = "icon_txts.png"
	STRONG[19]["ORDER"] = 2
	STRONG[19]["STRING"] = "go"
	STRONG[19]["STRING_2"] = "go"
	STRONG[19]["real_idx"] = 19

STRONG["index"][20] = 20
STRONG[20] = {}
	STRONG[20]["ID"] = 20
	STRONG[20]["TYPE"] = 5
	STRONG[20]["TAB"] = ""
	STRONG[20]["NAME"] = "strong name 20"
	STRONG[20]["SWITCHOVER"] = 2
	STRONG[20]["MEMO"] = ""
	STRONG[20]["CONDITION"] = "arena_open"
	STRONG[20]["FUNCTION_OPEN"] = ""
	STRONG[20]["BUILDING_NAME"] = ""
	STRONG[20]["TURN_TYPE"] = 6
	STRONG[20]["TURN_ID"] = 0
	STRONG[20]["ICON"] = "icon_txts.png"
	STRONG[20]["ORDER"] = 1
	STRONG[20]["STRING"] = "go"
	STRONG[20]["STRING_2"] = "go"
	STRONG[20]["real_idx"] = 20

STRONG["index"][21] = 21
STRONG[21] = {}
	STRONG[21]["ID"] = 21
	STRONG[21]["TYPE"] = 5
	STRONG[21]["TAB"] = 4
	STRONG[21]["NAME"] = "strong name 21"
	STRONG[21]["SWITCHOVER"] = 1
	STRONG[21]["MEMO"] = "strong memo 21"
	STRONG[21]["CONDITION"] = ""
	STRONG[21]["FUNCTION_OPEN"] = "dzgc_open"
	STRONG[21]["BUILDING_NAME"] = "BuildingName_16"
	STRONG[21]["TURN_TYPE"] = 2
	STRONG[21]["TURN_ID"] = 13
	STRONG[21]["ICON"] = "icon_txts.png"
	STRONG[21]["ORDER"] = 4
	STRONG[21]["STRING"] = "go"
	STRONG[21]["STRING_2"] = "go"
	STRONG[21]["real_idx"] = 21

STRONG["index"][22] = 22
STRONG[22] = {}
	STRONG[22]["ID"] = 22
	STRONG[22]["TYPE"] = 5
	STRONG[22]["TAB"] = 4
	STRONG[22]["NAME"] = "strong name 22"
	STRONG[22]["SWITCHOVER"] = 1
	STRONG[22]["MEMO"] = "strong memo 22"
	STRONG[22]["CONDITION"] = ""
	STRONG[22]["FUNCTION_OPEN"] = "dzgc_open"
	STRONG[22]["BUILDING_NAME"] = "BuildingName_16"
	STRONG[22]["TURN_TYPE"] = 2
	STRONG[22]["TURN_ID"] = 13
	STRONG[22]["ICON"] = "icon_txts.png"
	STRONG[22]["ORDER"] = 3
	STRONG[22]["STRING"] = "go"
	STRONG[22]["STRING_2"] = "go"
	STRONG[22]["real_idx"] = 22

STRONG["index"][23] = 23
STRONG[23] = {}
	STRONG[23]["ID"] = 23
	STRONG[23]["TYPE"] = 5
	STRONG[23]["TAB"] = 4
	STRONG[23]["NAME"] = "strong name 23"
	STRONG[23]["SWITCHOVER"] = 1
	STRONG[23]["MEMO"] = "strong memo 23"
	STRONG[23]["CONDITION"] = "league_open"
	STRONG[23]["FUNCTION_OPEN"] = ""
	STRONG[23]["BUILDING_NAME"] = ""
	STRONG[23]["TURN_TYPE"] = 21
	STRONG[23]["TURN_ID"] = 0
	STRONG[23]["ICON"] = "icon_txts.png"
	STRONG[23]["ORDER"] = 5
	STRONG[23]["STRING"] = "go"
	STRONG[23]["STRING_2"] = "join covenant"
	STRONG[23]["real_idx"] = 23


STRONG["len"] = 23

return STRONG
