local TRIAL_STORE = {}
TRIAL_STORE["index"] = {}
TRIAL_STORE["index"][1] = 1
TRIAL_STORE[1] = {}
	TRIAL_STORE[1]["ID"] = 1
	TRIAL_STORE[1]["ITEM_ID"] = 11001
	TRIAL_STORE[1]["ITEM_NUM"] = 1
	TRIAL_STORE[1]["BADGE"] = 150
	TRIAL_STORE[1]["TODAY_BUY"] = 0
	TRIAL_STORE[1]["ALL_BUY"] = 0
	TRIAL_STORE[1]["real_idx"] = 1

TRIAL_STORE["index"][2] = 2
TRIAL_STORE[2] = {}
	TRIAL_STORE[2]["ID"] = 2
	TRIAL_STORE[2]["ITEM_ID"] = 3001
	TRIAL_STORE[2]["ITEM_NUM"] = 500
	TRIAL_STORE[2]["BADGE"] = 10
	TRIAL_STORE[2]["TODAY_BUY"] = 0
	TRIAL_STORE[2]["ALL_BUY"] = 0
	TRIAL_STORE[2]["real_idx"] = 2

TRIAL_STORE["index"][3] = 3
TRIAL_STORE[3] = {}
	TRIAL_STORE[3]["ID"] = 3
	TRIAL_STORE[3]["ITEM_ID"] = 4001
	TRIAL_STORE[3]["ITEM_NUM"] = 1000
	TRIAL_STORE[3]["BADGE"] = 5
	TRIAL_STORE[3]["TODAY_BUY"] = 0
	TRIAL_STORE[3]["ALL_BUY"] = 0
	TRIAL_STORE[3]["real_idx"] = 3

TRIAL_STORE["index"][4] = 4
TRIAL_STORE[4] = {}
	TRIAL_STORE[4]["ID"] = 4
	TRIAL_STORE[4]["ITEM_ID"] = 5001
	TRIAL_STORE[4]["ITEM_NUM"] = 1000
	TRIAL_STORE[4]["BADGE"] = 20
	TRIAL_STORE[4]["TODAY_BUY"] = 0
	TRIAL_STORE[4]["ALL_BUY"] = 0
	TRIAL_STORE[4]["real_idx"] = 4

TRIAL_STORE["index"][5] = 5
TRIAL_STORE[5] = {}
	TRIAL_STORE[5]["ID"] = 5
	TRIAL_STORE[5]["ITEM_ID"] = 6001
	TRIAL_STORE[5]["ITEM_NUM"] = 1000
	TRIAL_STORE[5]["BADGE"] = 100
	TRIAL_STORE[5]["TODAY_BUY"] = 0
	TRIAL_STORE[5]["ALL_BUY"] = 0
	TRIAL_STORE[5]["real_idx"] = 5


TRIAL_STORE["len"] = 5

return TRIAL_STORE
