local WORSHIPREWARD = {}
WORSHIPREWARD["index"] = {}
WORSHIPREWARD["index"][1] = 1
WORSHIPREWARD[1] = {}
	WORSHIPREWARD[1]["ID"] = 1
	WORSHIPREWARD[1]["ACTIVE_POINT1"] = 200
	WORSHIPREWARD[1]["REWARD1"] = 1001
	WORSHIPREWARD[1]["ACTIVE_POINT2"] = 400
	WORSHIPREWARD[1]["REWARD2"] = 1002
	WORSHIPREWARD[1]["ACTIVE_POINT3"] = 800
	WORSHIPREWARD[1]["REWARD3"] = 1003
	WORSHIPREWARD[1]["MAX"] = 800
	WORSHIPREWARD[1]["real_idx"] = 1


WORSHIPREWARD["len"] = 1

return WORSHIPREWARD
