local ACTIVITY_TURNTABLE = {}
ACTIVITY_TURNTABLE["index"] = {}
ACTIVITY_TURNTABLE["index"][1] = 1
ACTIVITY_TURNTABLE[1] = {}
	ACTIVITY_TURNTABLE[1]["ID"] = 1
	ACTIVITY_TURNTABLE[1]["TPYE"] = 1
	ACTIVITY_TURNTABLE[1]["COST_NUM"] = 100
	ACTIVITY_TURNTABLE[1]["GET"] = 1
	ACTIVITY_TURNTABLE[1]["ITEM"] = {}
		ACTIVITY_TURNTABLE[1]["ITEM"][1] = 113004
		ACTIVITY_TURNTABLE[1]["ITEM"][2] = 18020
		ACTIVITY_TURNTABLE[1]["ITEM"][3] = 7001
		ACTIVITY_TURNTABLE[1]["ITEM"][4] = 17003
		ACTIVITY_TURNTABLE[1]["ITEM"][5] = 7001
		ACTIVITY_TURNTABLE[1]["ITEM"][6] = 17011
		ACTIVITY_TURNTABLE[1]["ITEM"][7] = 17002
		ACTIVITY_TURNTABLE[1]["ITEM"][8] = 7001
		ACTIVITY_TURNTABLE[1]["ITEM"][9] = 17001
		ACTIVITY_TURNTABLE[1]["ITEM"][10] = 7001
	ACTIVITY_TURNTABLE[1]["WEIGHT"] = {}
		ACTIVITY_TURNTABLE[1]["WEIGHT"][1] = 6
		ACTIVITY_TURNTABLE[1]["WEIGHT"][2] = 25
		ACTIVITY_TURNTABLE[1]["WEIGHT"][3] = 10
		ACTIVITY_TURNTABLE[1]["WEIGHT"][4] = 33
		ACTIVITY_TURNTABLE[1]["WEIGHT"][5] = 5
		ACTIVITY_TURNTABLE[1]["WEIGHT"][6] = 28
		ACTIVITY_TURNTABLE[1]["WEIGHT"][7] = 33
		ACTIVITY_TURNTABLE[1]["WEIGHT"][8] = 3
		ACTIVITY_TURNTABLE[1]["WEIGHT"][9] = 33
		ACTIVITY_TURNTABLE[1]["WEIGHT"][10] = 2
	ACTIVITY_TURNTABLE[1]["NUM"] = {}
		ACTIVITY_TURNTABLE[1]["NUM"][1] = 1
		ACTIVITY_TURNTABLE[1]["NUM"][2] = 8
		ACTIVITY_TURNTABLE[1]["NUM"][3] = 1000
		ACTIVITY_TURNTABLE[1]["NUM"][4] = 15
		ACTIVITY_TURNTABLE[1]["NUM"][5] = 2000
		ACTIVITY_TURNTABLE[1]["NUM"][6] = 6
		ACTIVITY_TURNTABLE[1]["NUM"][7] = 6
		ACTIVITY_TURNTABLE[1]["NUM"][8] = 3000
		ACTIVITY_TURNTABLE[1]["NUM"][9] = 1
		ACTIVITY_TURNTABLE[1]["NUM"][10] = 5000
	ACTIVITY_TURNTABLE[1]["SINGLE"] = 500
	ACTIVITY_TURNTABLE[1]["real_idx"] = 1


ACTIVITY_TURNTABLE["len"] = 1

return ACTIVITY_TURNTABLE
