local ACTIVITYSIGNIN = {}
ACTIVITYSIGNIN["index"] = {}
ACTIVITYSIGNIN["index"][1] = 1
ACTIVITYSIGNIN[1] = {}
	ACTIVITYSIGNIN[1]["ID"] = 1
	ACTIVITYSIGNIN[1]["NEXT_ID"] = 2
	ACTIVITYSIGNIN[1]["DATE"] = 1
	ACTIVITYSIGNIN[1]["GET"] = 3001
	ACTIVITYSIGNIN[1]["GET_NUM"] = 5000
	ACTIVITYSIGNIN[1]["real_idx"] = 1

ACTIVITYSIGNIN["index"][2] = 2
ACTIVITYSIGNIN[2] = {}
	ACTIVITYSIGNIN[2]["ID"] = 2
	ACTIVITYSIGNIN[2]["NEXT_ID"] = 3
	ACTIVITYSIGNIN[2]["DATE"] = 2
	ACTIVITYSIGNIN[2]["GET"] = 16001
	ACTIVITYSIGNIN[2]["GET_NUM"] = 3
	ACTIVITYSIGNIN[2]["real_idx"] = 2

ACTIVITYSIGNIN["index"][3] = 3
ACTIVITYSIGNIN[3] = {}
	ACTIVITYSIGNIN[3]["ID"] = 3
	ACTIVITYSIGNIN[3]["NEXT_ID"] = 4
	ACTIVITYSIGNIN[3]["DATE"] = 3
	ACTIVITYSIGNIN[3]["GET"] = 13001
	ACTIVITYSIGNIN[3]["GET_NUM"] = 15
	ACTIVITYSIGNIN[3]["real_idx"] = 3

ACTIVITYSIGNIN["index"][4] = 4
ACTIVITYSIGNIN[4] = {}
	ACTIVITYSIGNIN[4]["ID"] = 4
	ACTIVITYSIGNIN[4]["NEXT_ID"] = 5
	ACTIVITYSIGNIN[4]["DATE"] = 4
	ACTIVITYSIGNIN[4]["GET"] = 7001
	ACTIVITYSIGNIN[4]["GET_NUM"] = 40
	ACTIVITYSIGNIN[4]["real_idx"] = 4

ACTIVITYSIGNIN["index"][5] = 5
ACTIVITYSIGNIN[5] = {}
	ACTIVITYSIGNIN[5]["ID"] = 5
	ACTIVITYSIGNIN[5]["NEXT_ID"] = 6
	ACTIVITYSIGNIN[5]["DATE"] = 5
	ACTIVITYSIGNIN[5]["GET"] = 11001
	ACTIVITYSIGNIN[5]["GET_NUM"] = 60
	ACTIVITYSIGNIN[5]["real_idx"] = 5

ACTIVITYSIGNIN["index"][6] = 6
ACTIVITYSIGNIN[6] = {}
	ACTIVITYSIGNIN[6]["ID"] = 6
	ACTIVITYSIGNIN[6]["NEXT_ID"] = 7
	ACTIVITYSIGNIN[6]["DATE"] = 6
	ACTIVITYSIGNIN[6]["GET"] = 13005
	ACTIVITYSIGNIN[6]["GET_NUM"] = 80
	ACTIVITYSIGNIN[6]["real_idx"] = 6

ACTIVITYSIGNIN["index"][7] = 7
ACTIVITYSIGNIN[7] = {}
	ACTIVITYSIGNIN[7]["ID"] = 7
	ACTIVITYSIGNIN[7]["NEXT_ID"] = 0
	ACTIVITYSIGNIN[7]["DATE"] = 7
	ACTIVITYSIGNIN[7]["GET"] = 13002
	ACTIVITYSIGNIN[7]["GET_NUM"] = 8
	ACTIVITYSIGNIN[7]["real_idx"] = 7


ACTIVITYSIGNIN["len"] = 7

return ACTIVITYSIGNIN
