local REDEEMAWARD = {}
REDEEMAWARD["index"] = {}
REDEEMAWARD["index"][1] = 1
REDEEMAWARD[1] = {}
	REDEEMAWARD[1]["ID"] = 1
	REDEEMAWARD[1]["ITEM_ID"] = {}
		REDEEMAWARD[1]["ITEM_ID"][1] = 7001
		REDEEMAWARD[1]["ITEM_ID"][2] = 3001
		REDEEMAWARD[1]["ITEM_ID"][3] = 16001
		REDEEMAWARD[1]["ITEM_ID"][4] = 13001
	REDEEMAWARD[1]["ITEM_NUM"] = {}
		REDEEMAWARD[1]["ITEM_NUM"][1] = 188
		REDEEMAWARD[1]["ITEM_NUM"][2] = 88888
		REDEEMAWARD[1]["ITEM_NUM"][3] = 2
		REDEEMAWARD[1]["ITEM_NUM"][4] = 10
	REDEEMAWARD[1]["real_idx"] = 1


REDEEMAWARD["len"] = 1

return REDEEMAWARD
