lang=
{
	[650010001]= "武林外史",
	[650020002]= "陆小凤传奇",
	[650030003]= "萧十一郎",
	[650040004]= "七种武器",
	[650050005]= "圆月弯刀",
	[650060006]= "流星蝴蝶剑",
	[650070007]= "小李飞刀",
	[650080008]= "天涯明月刀",
	[650090009]= "绝代双骄",
	[650100010]= "楚留香传奇",
	
    notify1 = "{{#ffffff|*20}}恭喜{{#ffc341|*20}}%s{{#ffffff|*20}}在抽卡中获得稀有侠客{{#ffc341|*20}}%s",
    notify2 = "{{#ffc341|*20}}%s{{#ffffff|*20}}获得稀有侠客{{#ffc341|*20}}%s",
    notify3 = "{{#ffffff|*20}}恭喜{{#ffc341|*20}}%s{{#ffffff|*20}}在VIP礼包中获得了最强群攻侠客{{#ffc341|*20}}西门吹雪",
    notify4 = "{{#ffffff|*20}}一代名侠{{#ffc341|*20}}%s{{#ffffff|*20}}武力超群，勇夺比武榜第一，等待各路英豪前来挑战",
    notify5 = "{{#ffffff|*20}}恭喜{{#ffc341|*20}}%s{{#ffffff|*20}}获得超强力六星侠客{{#ba0f0f|*20}}%s",
    gm_sender = "迷之发件人",
    gm_subject = "迷之邮件",
    pvp_reward = "    你在比武时的表现技惊四座，令人过目不忘！截至今天21：00，你的比武排名为%d名。以下是你应得的奖励：",
    baixiaosheng = "百晓生",
    pvp_reward_subject = "比武每日排名奖励",
    pvp_rank_reward = "    你用无可比拟的精湛武艺又一次刷新了比武中的最高成绩！现在你的最高排名为第%d名，比之前提升了%d名，以下是你应得的奖励：",
    pvp_rank_reward_subject = "比武最高排名奖励",
    cjsz_mail51 = "        恭喜您在本次藏剑山庄活动内获得优异的成绩。以下是您的奖励，敬请笑纳。",
    cjsz_mail50 = "        恭喜在本次藏剑山庄活动内脱颖而出。在排行榜上位列%d名。以下是您的奖励，敬请笑纳。",
    youlongsheng = "游龙生",
    cjsz_subject = "藏剑山庄排行奖励",
    gl_yunying = "《古龙群侠传》运营团队",
    ext_mail_subject = "每日元宝大礼包",
    ext_mail_msg = "    这是今天赠予您的元宝大礼，请笑纳",
    bc20150321_sub = "精英副本奖励调整补偿",
    bc20150321_mail = "因精英副本的侠客碎片奖励调整，现将因调整损失的碎片以邮件形式进行补偿。",
	wboss_rank_reward_mail_subject = "巅峰对决排行奖励",
    wboss_rank_reward_mail_msg = "    恭喜大侠在巅峰对决中表现优异，位于伤害排行榜的第%d名。小小心意请大侠笑纳",
	wboss_rank_reward_mail_msg_2 = "    恭喜大侠在巅峰对决中展露头角。小小心意请大侠笑纳。",
	wboss_rank_reward_mail_subject_2 = "巅峰对决全服奖励",
	wboss_rank_reward_mail_msg_3 = "    在各位大侠的齐心协力下，成功战胜了武林名宿，其临走时留下对各位大侠的一份小小心意。请诸位笑纳。",
	jinjiuling = "古龙群侠传",
    haojiao20150401_subject = "免费号角发放",
    haojiao20150401_msg = "号角可以在聊天的世界频道中免费发言，请注意查收",
    group_mail_sender = "门派管理员",
    
    group_join_title = "成功加入门派",
    group_join_msg = "恭喜您通过层层考验，顺利成为%s的一员，快进入门派做出贡献吧！",  
    group_disband_title = "门派解散",
    group_disband_msg = "很遗憾，您的门派已被掌门解散，相关门派的积累会被清零，仅个人威望、门派奖章和独门绝学得以保留，请另谋高就。",
    group_kick_title = "离开门派",
    group_kick_msg = "很遗憾，您已被请离门派，相关门派的积累会被清零，仅个人威望、门派奖章和独门绝学得以保留，请另谋高就。",
    group_allot_title = "手动分配通知",
    group_allot_msg = "掌门已将战利品%s手动分配给了门派成员%s",
    group_allot2_title = "手动分配奖励",
    group_allot2_msg = "掌门已将战利品%s手动分配给您，请注意查收",
    group_auto_allot_title = "战利品发放",
    group_auto_allot_msg = "恭喜您按照战利品申请排序获得了%s，现在已可申请其他战利品。",
    group_rank_list_title = "累计伤害排名奖励",
    group_rank_list_msg = "您在%s中造成的累计伤害为：%d<$>对应的排名为：%d<$>以下是您的奖励：",
    group_fast_title = "快速通关奖励",
    group_fast_msg = "在门派成员的共同努力下，达成了%s快速通关的条件，以下是您的奖励：",
    group_master_title = "掌门转让",
    group_master_msg = "本门派掌门%s已将掌门之位转让给%s，特此公告",
    group_master_msg2 = "因原掌门连续72小时未有登陆，现系统根据职位和活跃度将掌门之位自动转让予%s",
    system_broadcast = "系统公告",
    
    cz_rank_global_mail_title = "神豪发红包",
    cz_rank_global_mail_msg = "神豪%s一掷千金，充值%d，获得活动积分：%d，并向全服发放红包好礼！",
    cz_rank_mail_title = "积分排行奖励",
    cz_rank_mail_msg = "恭喜你在活动期间成为本服的神豪。你的总积分为：%d，最终排名是：%d。以下是你的积分奖励：",
    
    sb_dayid = "%d月%d日登录礼包",
    msg_dayid = "尊敬的大侠<$>这是您今天的假日登录活动礼包，请查收，祝您游戏愉快",

    tianji_msg = "{{#ffffff|*20}}恭喜{{#ffc341|*20}}%s{{#ffffff|*20}}获得{{#ffc341|*20}}%s*%d",
}

lang_mpz = 
{
    mpz_sender = "《古龙群侠传》运营团队",
    mpz_reg_title = "血战报名奖励",
    mpz_reg_msg = "感谢报名血战，以下是对应的报名奖励。",
    mpz_fisrt_win_title = "初赛胜利奖励",
    mpz_fisrt_win_msg = "您的门派在初赛中顺利取胜，以下是对应的个人奖励。",
	mpz_fisrt_fail_title = "初赛失败奖励",
    mpz_fisrt_fail_msg = "您的门派在初赛中未能取胜，以下是对应的个人奖励。",
    mpz_second_win_title = "四强晋级奖励",
    mpz_second_win_msg = "您的门派在四强赛中顺利晋级，以下是对应的个人奖励。",
    mpz_second_fail_title = "四强淘汰奖励",
    mpz_second_fail_msg = "您的门派在四强赛中未能顺利晋级，以下是对应的个人奖励。",
    mpz_third_win_title = "血战冠军奖励",
    mpz_third_win_msg = "您的门派在血战中获得了第1名，以下是对应的个人奖励。",
    mpz_third_fail_title = "血战亚军奖励",
    mpz_third_fail_msg = "您的门派在血战中获得了第2名，以下是对应的个人奖励。",
    mpz_kuyin_title = "血战库银奖励",
    mpz_kuyin_msg1 = "您的门派在血战中获得相应库银：",
    mpz_kuyin_msg2 = "。",

    robot_gnickname = {
        "风云天下",
        "一剑飞仙",
        "天外飞仙",
        "万花门",
        "豪门天下",
        "侠客无敌",
        "古龙之家",
        "仁侠无敌",
    }
}
